import {
  IconClipboardList,
  IconTool,
  IconRoad,
  IconShield,
  IconTrafficLights,
  IconGasStation,
  IconBrain,
  IconHelmet,
  IconBeer,
  IconPill,
  IconWalk,
  IconScale,
  IconCar,
  IconCornerLeftUp,
  IconZzz,
  IconAlertTriangle,
  IconBulb,
  IconBike,
  IconMotorbike,
  IconCloudRain,
  IconUsersGroup,
  IconSquareLetterP,
  IconMoon,
  IconSteeringWheel,
  IconHeartHandshake,
  IconPackage,
  IconAmbulance,
  IconBabyCarriage,
  IconUser,
  IconSettings,
  IconCornerUpLeft,
  IconRuler,
  IconMountain,
  IconHandStop,
  IconBus,
  IconTrafficCone,
  IconTrain,
  IconHourglassLow,
  IconSnowflake,
  IconSchool,
  IconWorld,
  IconArrowsLeftRight,
  IconHorse,
  IconBuildingSkyscraper,
  IconTemperature,
  IconEye,
  IconSpeakerphone,
  IconRefresh,
  IconIdBadge2,
  IconCloudFog,
  IconGlassFull,
  IconDroplet,
  IconThermometer,
  IconSearch,
  IconCornerUpRight,
  IconFiretruck,
  IconBolt,
  IconBan,
  IconTruck,
  IconRocket,
  IconTractor,
  IconHelicopter,
  IconMan,
  IconWoman,
  IconMoodSmile,
  IconPointFilled,
  IconSquareRotatedFilled,
  IconDiamondFilled,
  IconMedal,
} from "@tabler/icons-react";

// Mapa de slug (guardado en pregunta.icono) -> componente de ícono Tabler
const ICON_MAP = {
  "clipboard-list": IconClipboardList,
  tool: IconTool,
  road: IconRoad,
  shield: IconShield,
  "traffic-lights": IconTrafficLights,
  "gas-station": IconGasStation,
  brain: IconBrain,
  helmet: IconHelmet,
  beer: IconBeer,
  pill: IconPill,
  walk: IconWalk,
  scale: IconScale,
  car: IconCar,
  "corner-left-up": IconCornerLeftUp,
  zzz: IconZzz,
  "alert-triangle": IconAlertTriangle,
  bulb: IconBulb,
  bike: IconBike,
  motorbike: IconMotorbike,
  "cloud-rain": IconCloudRain,
  "users-group": IconUsersGroup,
  "square-letter-p": IconSquareLetterP,
  moon: IconMoon,
  "steering-wheel": IconSteeringWheel,
  "heart-handshake": IconHeartHandshake,
  package: IconPackage,
  ambulance: IconAmbulance,
  "baby-carriage": IconBabyCarriage,
  user: IconUser,
  settings: IconSettings,
  "corner-up-left": IconCornerUpLeft,
  ruler: IconRuler,
  mountain: IconMountain,
  "hand-stop": IconHandStop,
  bus: IconBus,
  "traffic-cone": IconTrafficCone,
  train: IconTrain,
  "hourglass-low": IconHourglassLow,
  snowflake: IconSnowflake,
  school: IconSchool,
  world: IconWorld,
  "arrows-left-right": IconArrowsLeftRight,
  horse: IconHorse,
  "building-skyscraper": IconBuildingSkyscraper,
  temperature: IconTemperature,
  eye: IconEye,
  speakerphone: IconSpeakerphone,
  refresh: IconRefresh,
  "id-badge-2": IconIdBadge2,
  "cloud-fog": IconCloudFog,
  "glass-full": IconGlassFull,
  droplet: IconDroplet,
  thermometer: IconThermometer,
  search: IconSearch,
  "corner-up-right": IconCornerUpRight,
  firetruck: IconFiretruck,
  bolt: IconBolt,
  ban: IconBan,
  truck: IconTruck,
  rocket: IconRocket,
  tractor: IconTractor,
  helicopter: IconHelicopter,
  man: IconMan,
  woman: IconWoman,
  "mood-smile": IconMoodSmile,
  "point-filled": IconPointFilled,
  "square-rotated-filled": IconSquareRotatedFilled,
  "diamond-filled": IconDiamondFilled,
  medal: IconMedal,
};

/**
 * Renderiza el ícono Tabler correspondiente al slug guardado en pregunta.icono.
 * Si el slug no existe en el mapa, cae a IconClipboardList como fallback seguro.
 */
export default function QuestionIcon({ name, className = "w-5 h-5", ...props }) {
  const Icon = ICON_MAP[name] || IconClipboardList;
  return <Icon className={className} stroke={1.75} {...props} />;
}

export { ICON_MAP };
