// ─────────────────────────────────────────────────────────────────────────────
// BANCO DE PREGUNTAS — CLASES PROFESIONALES A1*, A2*, D, E
// Fuente: Cuestionario Base Examen Teórico Clases A1*, A2*, D, E — CONASET, enero 2016
// * Licencias Clase A1 y A2 otorgadas ANTES del 08 de marzo de 1997 (choferes profesionales
//   de la época). No confundir con las actuales licencias A1/A2 de motocicletas.
// D = Clase Especial D (taxis, transporte escolar, etc.) · E = Clase Especial E (remolques, etc.)
// ─────────────────────────────────────────────────────────────────────────────

export const PREGUNTAS_PROFESIONAL = [

  // ── CONDUCTA VIAL ──────────────────────────────────────────────────

  {
    id: 20001,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué parte de la vía debe utilizarse exclusivamente al conducir un vehículo?",
    opciones: ["La berma.", "La calzada.", "La acera."],
    correcta: 1,
    explicacion: "La alternativa correcta es «La calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20002,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿En qué casos puede usted circular por la berma con su vehículo?",
    opciones: ["Cuando por averías tenga que circular lentamente.", "Al estar las pistas ocupadas por otros vehículos.", "En ninguno de los casos anteriores."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En ninguno de los casos anteriores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20003,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Por dónde debe circular con su vehículo por norma general?",
    opciones: ["Por el centro de la calzada.", "Por la izquierda de la calzada.", "Por la derecha de la calzada."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Por la derecha de la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20004,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué obligación especial le corresponde a usted cuando circula en su vehículo en una vía de doble sentido de tránsito, al enfrentar a otro vehículo que transita en sentido contrario?",
    opciones: ["Circular por la derecha alejándose del eje de la calzada.", "Encender el intermitente.", "Reducir la velocidad."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Circular por la derecha alejándose del eje de la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20005,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué debe hacer usted al ser adelantado por otro vehículo?",
    opciones: ["Encender las luces bajas.", "Frenar bruscamente.", "Mantener su velocidad o disminuirla para permitir el adelantamiento."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Mantener su velocidad o disminuirla para permitir el adelantamiento.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20006,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Al estar las pistas de la calzada demarcadas, ¿por dónde debe circular con su vehículo?",
    opciones: ["Por el centro de la calzada.", "Por la derecha de la calzada, sin considerar las pistas.", "Dentro de la franja demarcada para la pista."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Dentro de la franja demarcada para la pista.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20007,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Al circular por una calzada con varias pistas demarcadas en un sentido de tránsito, para virar a la derecha, ¿qué maniobra debe efectuar?",
    opciones: ["Acercarse al eje central de la calzada.", "Ubicarse en la pista de la derecha de la calzada tan cerca como sea posible de la cuneta o del borde de la misma.", "Ubicarse en la pista de la izquierda de la calzada tan cerca como sea posible de la cuneta o del borde de la misma."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Ubicarse en la pista de la derecha de la calzada tan cerca como sea posible de la cuneta o del borde de la misma.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20008,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "De poder realizar la maniobra viraje en \"U\", ésta se puede hacer en:",
    opciones: ["Pasos peatonales.", "A mitad de cuadra si no está prohibido.", "En la intersección."],
    correcta: 1,
    explicacion: "La alternativa correcta es «A mitad de cuadra si no está prohibido.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20009,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Al encontrarse la calzada húmeda, con hielo o con pavimento resbaladizo por la lluvia, ¿qué debe hacer?",
    opciones: ["Conducir lenta y suavemente, sin hacer movimientos bruscos con el volante ni con los pedales.", "Aumentar la velocidad sin hacer movimientos bruscos con el volante.", "Estar atento a frenar."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Conducir lenta y suavemente, sin hacer movimientos bruscos con el volante ni con los pedales.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20010,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Al aproximarse a una curva con visibilidad reducida, ¿qué debe hacer?",
    opciones: ["Adaptar la velocidad y ceñirse al borde derecho de la calzada.", "Circular por el centro de la calzada.", "Disminuir la velocidad hasta detenerse."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Adaptar la velocidad y ceñirse al borde derecho de la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20011,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Si observa que en la parte trasera de un vehículo se encienden las luces blancas, ¿qué indica?",
    opciones: ["Que el vehículo va a adelantar a otro vehículo.", "Que está retrocediendo.", "Que está virando a la derecha."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Que está retrocediendo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20012,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Qué distancia puede recorrer un vehículo en marcha atrás por la calzada?",
    opciones: ["100 metros.", "150 metros.", "Ninguna de las anteriores."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Ninguna de las anteriores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20013,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Para adelantar, ¿qué norma general debe considerar?",
    opciones: ["Adelantar por la derecha.", "Adelantar por la izquierda.", "En zonas rurales adelantar por la berma, al estar el vehículo que antecede detenido."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Adelantar por la izquierda.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20014,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué maniobra debe realizar, al circular por una vía de dos sentidos, si va a girar hacia la izquierda?",
    opciones: ["Situarse al costado derecho de la calzada.", "Situarse progresivamente al costado derecho del eje o línea central de la vía por donde transita.", "Situarse al costado izquierdo de la calzada."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Situarse progresivamente al costado derecho del eje o línea central de la vía por donde transita.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20015,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Por regla general, ¿cómo debe estacionar su vehículo?",
    opciones: ["Con dos ruedas sobre la acera.", "Sobre la acera.", "Al lado derecho en el sentido del tránsito, sobre la calzada."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Al lado derecho en el sentido del tránsito, sobre la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20016,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En las vías rurales, por regla general, ¿cómo debe estacionar su vehículo?",
    opciones: ["Con toda la estructura del vehículo sobre la berma.", "Sobre la calzada en el sentido contrario del tránsito.", "Longitudinalmente con la mitad del vehículo sobre la berma."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Con toda la estructura del vehículo sobre la berma.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20017,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Puede usted conducir sin licencia?",
    opciones: ["Sí, en caminos públicos rurales durante el día.", "Sí, en lugares de poco tránsito en las vías públicas de la ciudad.", "En ninguno de los casos anteriores."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En ninguno de los casos anteriores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20018,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Al transitar con su vehículo, usted podrá pasar con luz roja del semáforo:",
    opciones: ["Si no hay vehículos que pasen con verde.", "Si su vehículo es destinado a transporte de pasajeros.", "En ningún caso."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En ningún caso.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20019,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Puede usted conducir un vehículo de distinto tipo a la licencia que posee por la vía pública en alguno de los siguientes casos?",
    opciones: ["Para efectuar viajes cortos.", "En zonas no controladas.", "En ninguno de los casos anteriores."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En ninguno de los casos anteriores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20020,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿De qué forma estaciona el vehículo en bajada?",
    opciones: ["Sólo con freno de mano.", "Enganchado en primera marcha.", "Con freno de mano y las ruedas delanteras giradas hacia la cuneta."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Con freno de mano y las ruedas delanteras giradas hacia la cuneta.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20021,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Usted puede conducir su vehículo en las vías públicas:",
    opciones: ["Sin sistemas de frenos.", "Con el mecanismo de la dirección en mal estado.", "En ninguno de los casos anteriores."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En ninguno de los casos anteriores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20022,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Usted al transitar con su vehículo en las vías rurales, como norma de carácter general, durante la noche debe hacerlo con:",
    opciones: ["Luces altas.", "Luces bajas.", "Luces de estacionamiento."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Luces altas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20023,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Usted al conducir su vehículo durante la noche, por regla general, en la zonas urbanas debe hacerlo con:",
    opciones: ["Luces de estacionamiento solamente.", "Luces altas.", "Luces bajas."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Luces bajas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20024,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Usted al conducir su vehículo podrá usar la bocina para:",
    opciones: ["Apurar al vehículo que le antecede.", "Anunciar que estacionará.", "Prevenir un accidente, si ello es estrictamente necesario."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Prevenir un accidente, si ello es estrictamente necesario.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20025,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Si la parte trasera de su vehículo patina hacia un costado usted:",
    opciones: ["Frena bruscamente.", "Gira las ruedas delanteras en el mismo sentido de la patinada.", "Gira las ruedas delanteras en sentido contrario a la patinada."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Gira las ruedas delanteras en el mismo sentido de la patinada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20026,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "Usted al transitar con su vehículo podrá no tener espejo retrovisor interior en los siguientes casos:",
    opciones: ["Cuando transite a baja velocidad.", "Cuando su vehículo es de transporte de carga.", "En ninguno de los casos anteriores."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Cuando su vehículo es de transporte de carga.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  // ── MECÁNICA DIÉSEL ──────────────────────────────────────────────────

  {
    id: 20027,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "El consumo de combustible y la duración de los motores Diésel son como se indica:",
    opciones: ["Mayores que en motores a bencina.", "Consumo mayor y duración menor que en motores a bencina.", "Consumo menor y duración mayor que en motores a bencina."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Consumo menor y duración mayor que en motores a bencina.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20028,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La emisión de monóxido de carbono y el número de revoluciones del motor Diésel son:",
    opciones: ["Mayores que en motores a bencina.", "Iguales que en motores a bencina.", "Menores que en el motor a bencina."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Menores que en el motor a bencina.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20029,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La ignición de la mezcla se produce:",
    opciones: ["Con una bujía.", "Por la sola compresión del aire.", "Por la compresión del aire e inyección del petróleo."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Por la compresión del aire e inyección del petróleo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20030,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Durante la carrera de compresión:",
    opciones: ["Se comprime la mezcla de aire y petróleo.", "Se comprime aire.", "Se comprime petróleo pulverizado."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Se comprime aire.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20031,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Como práctica de conducir, acelerar rápidamente un motor Diésel es:",
    opciones: ["Conveniente, pues así se produce un menor desgaste de los inyectores.", "Inconveniente, pues se produce un mayor desgaste de los anillos.", "Inconveniente, pues se produce una combustión incompleta."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Inconveniente, pues se produce una combustión incompleta.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20032,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Los motores Diésel funcionan básicamente con:",
    opciones: ["Inyectores.", "Carburador igual al del motor a bencina.", "Un carburador especial."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Inyectores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20033,
    categoria: "Mecánica Diésel",
    icono: "gas-station",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Los filtros de combustible sirven para evitar:",
    opciones: ["Desgaste de partes vitales del motor.", "Ahogamiento del motor.", "Humo en el escape."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Desgaste de partes vitales del motor.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  // ── MECÁNICA BÁSICA ──────────────────────────────────────────────────

  {
    id: 20034,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Si el alternador de corriente del vehículo no carga, ¿qué pasa?",
    opciones: ["El motor deja de funcionar.", "Se descarga la batería.", "Se produce un desgaste rápido en los electrodos de las bujías."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Se descarga la batería.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20035,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Cuando la rueda del vehículo se calienta, indica:",
    opciones: ["Pedal de freno llega a fondo.", "Roza la balata (pastillas) por estar muy ajustadas.", "Falta de líquido de frenos."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Roza la balata (pastillas) por estar muy ajustadas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20036,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "El nombre que recibe el marcador de revoluciones del motor es:",
    opciones: ["Manómetro.", "Tacómetro.", "Pluviómetro."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Tacómetro.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20037,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "El nivel correcto de electrolito en una batería es:",
    opciones: ["1 cm. bajo el nivel de las placas.", "Al nivel de las placas.", "Sobre 1 cm. del nivel de las placas."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Sobre 1 cm. del nivel de las placas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20038,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Si se corta la correa del ventilador:",
    opciones: ["El motor no funciona.", "El motor se calienta.", "El motor funciona sólo en baja velocidad."],
    correcta: 1,
    explicacion: "La alternativa correcta es «El motor se calienta.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20039,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La función del embrague es:",
    opciones: ["Frenar el motor del vehículo.", "Darle fuerza al motor del vehículo.", "Conectar y desconectar \"la fuerza\" del motor a la caja de velocidades."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Conectar y desconectar \"la fuerza\" del motor a la caja de velocidades.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20040,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Una de las causas de que el motor de arranque no funcione es:",
    opciones: ["Cables de las bujías desconectados.", "Bobina en mal estado.", "Bornes de la batería sulfatados."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Bornes de la batería sulfatados.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20041,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "El exceso de inflado en un neumático produce:",
    opciones: ["Desgaste en los bordes de la banda de rodamiento.", "Desgaste en el centro de la banda de rodamiento del neumático.", "Deterioro de la válvula de inflado."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Desgaste en el centro de la banda de rodamiento del neumático.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20042,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "El desgaste disparejo de los neumáticos delanteros se debe a:",
    opciones: ["Exceso de velocidad en zonas de curvas.", "Exceso de peso en el vehículo.", "Deficiente alineación del tren delantero y/o desgaste de amortiguadores."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Deficiente alineación del tren delantero y/o desgaste de amortiguadores.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20043,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Conducir sin retirar totalmente el pie del pedal de embrague produce:",
    opciones: ["Desgaste en el motor del vehículo.", "Menor fuerza en el motor.", "Desgaste prematuro en balata del embrague."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Desgaste prematuro en balata del embrague.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20044,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La excesiva temperatura en la batería puede deberse a:",
    opciones: ["Deficiente funcionamiento del regulador de voltaje.", "Poca chispa en las bujías.", "Demasiada agua destilada."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Deficiente funcionamiento del regulador de voltaje.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20045,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Si con el motor funcionado se enciende la luz roja indicadora de presión de aceite, se debe:",
    opciones: ["Continuar la marcha.", "Detener inmediatamente el vehículo y el motor.", "Continuar muy lentamente."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Detener inmediatamente el vehículo y el motor.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20046,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Circulando con el vehículo se detecta que el motor se sobrecalienta; ello se puede deber a:",
    opciones: ["Circuito de refrigeración obstruido.", "Insuficiente paso de agua caliente al radiador de la calefacción.", "Batería con baja carga."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Circuito de refrigeración obstruido.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20047,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Indique el modo más simple de limpiar los bornes sulfatados de la batería:",
    opciones: ["Ácido sulfúrico.", "Agua con bicarbonato.", "Agua destilada."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Agua con bicarbonato.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20048,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Si durante la marcha del vehículo, se desconecta un cable de bujía:",
    opciones: ["El motor no funciona.", "El motor pierde fuerza.", "El motor gira la mitad de las revoluciones normales."],
    correcta: 1,
    explicacion: "La alternativa correcta es «El motor pierde fuerza.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20049,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "En una pendiente (bajada) pronunciada, se debe:",
    opciones: ["Utilizar permanentemente el freno de pie.", "Enganchar en el cambio de velocidad correspondiente.", "Presionar el pedal de embrague."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Enganchar en el cambio de velocidad correspondiente.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20050,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Cuando el tubo de escape expele humo \"azul\" significa que el vehículo está:",
    opciones: ["Mal carburado.", "Con motor fuera de punto en el encendido.", "Quemando aceite."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Quemando aceite.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20051,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Si el motor está sobrecalentado por falta de agua en el sistema de refrigeración:",
    opciones: ["Se le agrega agua lentamente con el motor funcionando.", "No se le agrega agua.", "Se le agrega agua con el motor detenido."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Se le agrega agua lentamente con el motor funcionando.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20052,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Al subir una cuesta en un cambio de velocidad no adecuado se produce:",
    opciones: ["Falla en el sistema de frenos.", "Falla en la caja de cambios.", "Exceso de consumo de combustible."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Exceso de consumo de combustible.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20053,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Cuando un neumático delantero tiene baja presión:",
    opciones: ["La dirección del vehículo tiende hacia un lado.", "El motor pierde potencia.", "Se sobrecalienta el motor."],
    correcta: 0,
    explicacion: "La alternativa correcta es «La dirección del vehículo tiende hacia un lado.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20054,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "El que los frenos rocen puede deberse a:",
    opciones: ["Mala regulación del pedal de freno.", "La falta de líquido de freno.", "Mala regulación de balatas o pastillas."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Mala regulación de balatas o pastillas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20055,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Para que las bandas de los neumáticos se desgasten en forma pareja se debe efectuar:",
    opciones: ["Un recauchado cada 10.000 kilómetros.", "Una rotación periódica.", "Un redibujado cada 15.000 kilómetros."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Una rotación periódica.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20056,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Antes de poner un vehículo en marcha, el conductor debe verificar:",
    opciones: ["El funcionamiento del tubo de escape.", "El funcionamiento del freno, embrague e instrumentos del tablero.", "El estado de la carrocería."],
    correcta: 1,
    explicacion: "La alternativa correcta es «El funcionamiento del freno, embrague e instrumentos del tablero.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20057,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "Lo que recibe la fuerza de la explosión en un motor se denomina:",
    opciones: ["Pistón.", "Biela.", "Cigüeñal."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Pistón.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20058,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La función del filtro de aceite es:",
    opciones: ["Restituir la viscosidad del aceite.", "Retener las partículas gruesas del aceite.", "Separar el combustible del aceite."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Retener las partículas gruesas del aceite.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20059,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La función del filtro de aire es:",
    opciones: ["Separar el aire del aceite.", "Separar el aire del combustible.", "Retener las partículas contenidas en el aire, antes de entrar al carburador."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Retener las partículas contenidas en el aire, antes de entrar al carburador.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20060,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    clases: ["A1", "A2"],
    pregunta: "La falta de presión en los neumáticos produce:",
    opciones: ["Desgaste en el centro de la banda de rodamiento.", "Desgaste en los costados de la banda de rodamiento.", "Ninguna de las anteriores."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Desgaste en los costados de la banda de rodamiento.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  // ── CONOCIMIENTOS LEGALES ──────────────────────────────────────────────────

  {
    id: 20061,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Cuándo los conductores deben mantenerse atentos a las condiciones de tránsito del momento?",
    opciones: ["Siempre.", "Sólo en días de lluvia y niebla.", "Sólo en la noche."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Siempre.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20062,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Una persona puede manejar un vehículo bajo la influencia del alcohol...",
    opciones: ["Nunca.", "Sólo de día.", "Sin estar ebrio."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Nunca.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20063,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En condiciones normales un vehículo podrá ser conducido marcha atrás sólo:",
    opciones: ["50 metros.", "30 metros.", "Para mantener la libre circulación o para incorporarse a ella o estacionar un vehículo."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Para mantener la libre circulación o para incorporarse a ella o estacionar un vehículo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20064,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Los vehículos deberán circular por la mitad derecha de la calzada, salvo en el siguiente caso, entre otros:",
    opciones: ["En circulación rural, cuando la velocidad sea menor a 45 km/h.", "En circulación urbana, cuando la velocidad sea menor a 45 km/h.", "En la circulación urbana, cuando la calzada está exclusivamente señalizada para el tránsito en un sólo sentido."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En la circulación urbana, cuando la calzada está exclusivamente señalizada para el tránsito en un sólo sentido.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20065,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En vías de doble tránsito, los vehículos que circulen en sentido opuesto, al cruzarse:",
    opciones: ["Deberán encender las luces bajas.", "Deberán señalizar con los brazos.", "No pasarán sobre el eje de la calzada, demarcado o imaginario."],
    correcta: 2,
    explicacion: "La alternativa correcta es «No pasarán sobre el eje de la calzada, demarcado o imaginario.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20066,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "El conductor de un vehículo puede sobrepasar a otro por la derecha, cuando:",
    opciones: ["El vehículo de adelante va a virar a la derecha.", "El vehículo de adelante va a virar a la izquierda.", "Nunca."],
    correcta: 1,
    explicacion: "La alternativa correcta es «El vehículo de adelante va a virar a la izquierda.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20067,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "No se podrá adelantar en el siguiente caso:",
    opciones: ["Al aproximarse un camión.", "Cuando existe eje discontinuo.", "Al aproximarse a la cima de una cuesta."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Al aproximarse a la cima de una cuesta.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20068,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Cuál es la distancia que debe mantener un conductor con respecto al vehículo de adelante?",
    opciones: ["30 mts.", "100 mts.", "Una distancia razonable y prudente."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Una distancia razonable y prudente.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20069,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Cuando los vehículos circulan en caravana o convoy, la distancia entre los vehículos será:",
    opciones: ["Entre 1 a 4 metros.", "La suficiente para que cualquier vehículo que los adelante pueda ocupar la vía sin peligro.", "Ninguna, no se puede circular en caravana o convoy."],
    correcta: 1,
    explicacion: "La alternativa correcta es «La suficiente para que cualquier vehículo que los adelante pueda ocupar la vía sin peligro.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20070,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué deberá hacer un conductor al iniciar un viraje a la derecha?",
    opciones: ["Acercarse lo más a la izquierda posible.", "Hacerlo desde la pista central.", "Acercarse lo más a la derecha posible."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Acercarse lo más a la derecha posible.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20071,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué deberá hacer un conductor al iniciar un viraje a la izquierda desde una vía de doble tránsito?",
    opciones: ["Aproximarse al costado derecho del eje o de la línea central de la vía por donde transita.", "Ubicarse al lado izquierdo del eje de la calzada.", "Acercarse lo más a la derecha posible."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Aproximarse al costado derecho del eje o de la línea central de la vía por donde transita.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20072,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Se prohibe efectuar viraje en \"U\" en el siguiente caso:",
    opciones: ["A mitad de cuadra.", "A 300 mts. de una curva.", "En los pasos de peatones."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En los pasos de peatones.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20073,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Para señalizar con el brazo el viraje a la izquierda, se coloca el brazo:",
    opciones: ["Extendido horizontalmente.", "En ángulo recto hacia arriba.", "Hacia abajo."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Extendido horizontalmente.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20074,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Para señalizar con el brazo la disminución de la velocidad o detención del vehículo se debe poner:",
    opciones: ["El brazo extendido horizontalmente.", "El brazo en ángulo recto hacia arriba.", "El brazo extendido hacia abajo."],
    correcta: 2,
    explicacion: "La alternativa correcta es «El brazo extendido hacia abajo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20075,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "¿Cuándo la carga podrá exceder los pesos máximos que las características técnicas del vehículo permitan?",
    opciones: ["Siempre.", "Cuando se pone carga líquida.", "Nunca."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Nunca.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20076,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "La carga deberá ser estibada y asegurada de manera que:",
    opciones: ["Evite todo riesgo de caída desde el vehículo.", "No se produzcan robos.", "No se deteriore por el sol."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Evite todo riesgo de caída desde el vehículo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20077,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "¿Cuándo se puede transportar pasajeros en vehículos de carga?",
    opciones: ["Nunca.", "Siempre.", "Sólo en casos justificados y adoptando medidas de seguridad adecuadas."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Sólo en casos justificados y adoptando medidas de seguridad adecuadas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20078,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1"],
    pregunta: "¿Cuándo se podrán transportar materias peligrosas en vehículos de alquiler o en los destinados al transporte colectivo?",
    opciones: ["Cuando vayan en un envase firme.", "Nunca.", "Sólo cuando el vehículo lleve pocos pasajeros."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Nunca.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20079,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "El color de las luces que proyecten hacia delante los vehículos debe ser:",
    opciones: ["Rojas y blancas.", "Blancas o amarillas.", "Rojas o blancas."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Blancas o amarillas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20080,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿De qué color deben ser las luces de viraje traseras?",
    opciones: ["Blancas.", "Rojas o amarillas.", "Verdes."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Rojas o amarillas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20081,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Qué focos o luces se prohíben?",
    opciones: ["Los neblineros.", "Los busca-caminos.", "Todos los que induzcan a error en la conducción."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Todos los que induzcan a error en la conducción.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20082,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Los vehículos deberán llevar encendidas las luces reglamentarias desde:",
    opciones: ["Media hora antes de la puesta de sol, hasta media hora antes de su salida.", "Media hora después de la puesta de sol, hasta media hora antes de su salida.", "Ninguna de las anteriores."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Media hora después de la puesta de sol, hasta media hora antes de su salida.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20083,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Cuándo se puede hacer uso del aparato sonoro en zona rural?",
    opciones: ["Sólo en caso necesario.", "Al llegar a una curva.", "Al entrar a un túnel."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Sólo en caso necesario.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20084,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Los vehículos que tengan sus neumáticos con las bandas de rodadura desgastadas:",
    opciones: ["Podrán circular sólo de noche.", "Podrán circular sólo en días despejados.", "No podrán circular."],
    correcta: 2,
    explicacion: "La alternativa correcta es «No podrán circular.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20085,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Cuántos sistemas de frenos debe tener un vehículo motorizado?",
    opciones: ["A lo menos dos, independientes entre sí.", "Dos, conectados entre sí.", "A lo menos uno."],
    correcta: 0,
    explicacion: "La alternativa correcta es «A lo menos dos, independientes entre sí.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20086,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Qué tipos de vehículos deben llevar luces amarillas frontales, que indiquen claramente ancho y altura máxima del vehículo?",
    opciones: ["Todos los vehículos.", "Sólo los de carga.", "Los vehículos de 2 o más metros de ancho."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Los vehículos de 2 o más metros de ancho.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20087,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Qué luces debe llevar el vehículo en las vías públicas urbanas?",
    opciones: ["Luces altas.", "Luces bajas.", "Cualquier tipo de luz."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Luces bajas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20088,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "Cuando se circule de noche por caminos y vías rurales con luces encendidas y no se encuentre próximo ningún otro vehículo, se utilizarán luces:",
    opciones: ["Altas y bajas.", "Altas.", "Bajas."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Altas.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20089,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Qué tipo de luces no se deben usar cuando el vehículo se encuentre en movimiento?",
    opciones: ["De estacionamiento.", "De freno.", "De viraje."],
    correcta: 0,
    explicacion: "La alternativa correcta es «De estacionamiento.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20090,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿En qué parte del túnel se puede hacer uso del aparato sonoro?",
    opciones: ["A la entrada.", "A la salida.", "En ninguna parte."],
    correcta: 2,
    explicacion: "La alternativa correcta es «En ninguna parte.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20091,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "En general, ¿cómo deben ser los sistemas de frenos de un vehículo con remolque, con capacidad de carga superior a 750 kg.?",
    opciones: ["Independientes, accionados desde el vehículo tractor.", "Independientes, accionados desde el remolque.", "Ninguna de las anteriores."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Independientes, accionados desde el vehículo tractor.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20092,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "Si el remolque se desprende del vehículo tractor, ¿cómo deberán accionarse los frenos?",
    opciones: ["Manualmente.", "Automáticamente.", "No deberán accionarse."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Automáticamente.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20093,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2"],
    pregunta: "Las características que deben cumplir los vidrios de seguridad en un vehículo son:",
    opciones: ["Permitir relativa visibilidad desde el interior.", "Permitir perfecta visibilidad desde el exterior.", "Permitir perfecta visibilidad desde y hacia el interior del vehículo."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Permitir perfecta visibilidad desde y hacia el interior del vehículo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20094,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2"],
    pregunta: "¿En qué condiciones debe estar la rueda de repuesto?",
    opciones: ["En buen estado.", "Redibujada.", "Recauchada lisa."],
    correcta: 0,
    explicacion: "La alternativa correcta es «En buen estado.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20095,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2"],
    pregunta: "De los siguientes elementos, ¿cuáles deben portarse en los vehículos de locomoción colectiva y de carga?",
    opciones: ["Sólo botiquín, dos cuñas de seguridad y chaleco reflectante.", "Botiquín, dos cuñas de seguridad, triángulo reflectante, extintor (es) de incendio y chaleco reflectante.", "Sólo botiquín, dos cuñas de seguridad, chaleco reflectante y extintor (es) de incendio."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Botiquín, dos cuñas de seguridad, triángulo reflectante, extintor (es) de incendio y chaleco reflectante.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20096,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1"],
    pregunta: "La profundidad mínima de las bandas de rodamiento de los neumáticos de taxis debe ser de:",
    opciones: ["3 mm.", "2 mm.", "1,6 mm."],
    correcta: 2,
    explicacion: "La alternativa correcta es «1,6 mm.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20097,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1"],
    pregunta: "En el caso de un servicio de transporte público interurbano de pasajeros, ¿cuánto tiempo como mínimo deben mantenerse los registros del tacógrafo o dispositivo electrónico equivalente?",
    opciones: ["30 días.", "60 días.", "90 días."],
    correcta: 1,
    explicacion: "La alternativa correcta es «60 días.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20098,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Adelantamiento es la maniobra efectuada:",
    opciones: ["Por el costado izquierdo del eje de la calzada.", "Por la berma del costado derecho.", "Por el costado derecho del eje de la calzada."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Por el costado izquierdo del eje de la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20099,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Cruce regulado es aquel en que existe:",
    opciones: ["Señal PARE o CEDA EL PASO.", "Semáforo intermitente.", "Semáforo funcionando normalmente o Carabinero dirigiendo el tránsito."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Semáforo funcionando normalmente o Carabinero dirigiendo el tránsito.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20100,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Derecho preferente de paso es:",
    opciones: ["La prerrogativa de un peatón o conductor de un vehículo para proseguir su marcha.", "Virar careciendo de preferencia.", "Virar a la izquierda sin detener la marcha."],
    correcta: 0,
    explicacion: "La alternativa correcta es «La prerrogativa de un peatón o conductor de un vehículo para proseguir su marcha.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20101,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "El eje de la calzada es:",
    opciones: ["La línea perpendicular a la calzada, demarcada o imaginaria que determina las áreas con sentido de tránsito opuesto.", "La línea longitudinal a la calzada, demarcada o imaginaria que determina las áreas con sentido de tránsito opuesto.", "La línea longitudinal formada por la prolongación de las líneas de edificación."],
    correcta: 1,
    explicacion: "La alternativa correcta es «La línea longitudinal a la calzada, demarcada o imaginaria que determina las áreas con sentido de tránsito opuesto.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20102,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Estacionar es:",
    opciones: ["Detener momentáneamente un vehículo en la vía pública, con o sin el conductor dentro de él.", "Ubicar el vehículo en un lugar determinado.", "Paralizar un vehículo en la vía pública, con o sin el conductor, por un período mayor que el necesario para dejar o recibir pasajeros."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Paralizar un vehículo en la vía pública, con o sin el conductor, por un período mayor que el necesario para dejar o recibir pasajeros.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20103,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Intersección es:",
    opciones: ["El área común de calzadas que no se cruzan o divergen.", "El área común de calzadas que se cruzan o convergen.", "Ninguna de las anteriores."],
    correcta: 1,
    explicacion: "La alternativa correcta es «El área común de calzadas que se cruzan o convergen.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20104,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Línea de detención de vehículos es:",
    opciones: ["La línea transversal a la calzada, demarcada o imaginaria, ubicada antes de un paso para peatones o de una intersección.", "El paso de cebra.", "La línea imaginaria ubicada a menos de un metro después del paso de peatones."],
    correcta: 0,
    explicacion: "La alternativa correcta es «La línea transversal a la calzada, demarcada o imaginaria, ubicada antes de un paso para peatones o de una intersección.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20105,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Paso de peatones es:",
    opciones: ["La senda de seguridad formada por la prolongación imaginaria o demarcada de las aceras.", "La senda formada por la prolongación de las líneas de detención.", "La senda de seguridad en la calzada señalizada conforme al reglamento."],
    correcta: 2,
    explicacion: "La alternativa correcta es «La senda de seguridad en la calzada señalizada conforme al reglamento.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20106,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Sobrepasar es:",
    opciones: ["Situarse detrás de otro vehículo, sobrepasando el eje de la calzada.", "Pasar a otro u otros vehículos en el mismo sentido, sin traspasar el eje de la calzada.", "Situarse delante de otro vehículo, traspasando el eje de la calzada."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Pasar a otro u otros vehículos en el mismo sentido, sin traspasar el eje de la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20107,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En un cruce no regulado, ¿qué vehículo deberá ceder el derecho preferente de paso?",
    opciones: ["El que llega primero al cruce.", "El de la derecha con respecto al que se acerque por la izquierda.", "El de la izquierda con respecto al que se acerque por la derecha."],
    correcta: 2,
    explicacion: "La alternativa correcta es «El de la izquierda con respecto al que se acerque por la derecha.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20108,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Un conductor, al enfrentar un signo \"PARE\", deberá:",
    opciones: ["Proseguir su marcha.", "Detenerse.", "Encender luces altas."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Detenerse.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20109,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Un conductor, al enfrentar un signo \"CEDA EL PASO\", deberá:",
    opciones: ["Detenerse siempre.", "Seguir a la misma velocidad.", "Reducir la velocidad y detenerse si fuese necesario."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Reducir la velocidad y detenerse si fuese necesario.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20110,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Un vehículo que se incorpore a la circulación desde un garage particular, carece del derecho preferente de paso:",
    opciones: ["Cuando el vehículo es un camión.", "Siempre.", "Ninguna de las anteriores."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Siempre.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20111,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Cuando se aproxima un vehículo de emergencia haciendo uso de sus señales audibles y visibles en el mismo sentido, el conductor deberá:",
    opciones: ["Acelerar y circular delante del vehículo de emergencia.", "Frenar bruscamente.", "Conducir el vehículo lo más a la izquierda o a la derecha posible, con el objeto de despejar la vía."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Conducir el vehículo lo más a la izquierda o a la derecha posible, con el objeto de despejar la vía.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20112,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Por regla general, los vehículos deberán estacionarse:",
    opciones: ["A la derecha de la calzada.", "Al centro de la calzada.", "A la izquierda de la calzada."],
    correcta: 0,
    explicacion: "La alternativa correcta es «A la derecha de la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20113,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Sólo se podrá estacionar al lado izquierdo de la calzada cuando:",
    opciones: ["La señalización lo permita.", "No haya Carabineros en el lugar.", "Ninguna de las anteriores."],
    correcta: 0,
    explicacion: "La alternativa correcta es «La señalización lo permita.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20114,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En la carretera, los vehículos deberán estacionarse:",
    opciones: ["Con la mitad derecha sobre la berma.", "Sólo con la parte de atrás sobre la calzada.", "Con toda su estructura sobre la berma."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Con toda su estructura sobre la berma.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20115,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Cuál es la distancia máxima a la que deben estacionarse los vehículos de la cuneta?",
    opciones: ["20 cm.", "60 cm.", "30 cm."],
    correcta: 2,
    explicacion: "La alternativa correcta es «30 cm.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20116,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Qué deberá hacer un conductor al estacionar un vehículo motorizado?",
    opciones: ["Detener el motor del vehículo.", "Frenarlo y detener el motor.", "Frenar el vehículo."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Frenarlo y detener el motor.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20117,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "La distancia mínima entre un vehículo y otro al estacionarse debe ser de:",
    opciones: ["50 cm.", "60 cm.", "30 cm."],
    correcta: 1,
    explicacion: "La alternativa correcta es «60 cm.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20118,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿A cuántos metros de un grifo para incendio y de un cuartel de bombas se puede estacionar un vehículo?",
    opciones: ["A menos de 6 metros y 5 metros, respectivamente.", "A más de un metro y 3 metros, respectivamente.", "A más de 5 metros y 10 metros, respectivamente."],
    correcta: 2,
    explicacion: "La alternativa correcta es «A más de 5 metros y 10 metros, respectivamente.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20119,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿A cuántos metros de un cruce ferroviario a nivel se puede estacionar?",
    opciones: ["A más de 5 metros.", "A más de 20 metros.", "A menos de 20 metros."],
    correcta: 1,
    explicacion: "La alternativa correcta es «A más de 20 metros.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20120,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿A cuántos metros de una esquina y de un signo PARE o CEDA EL PASO se puede estacionar un vehículo motorizado?",
    opciones: ["A más de 10 metros, en ambos casos.", "A menos de 10 y 5 metros, respectivamente.", "A más de 5 y 10 metros, respectivamente."],
    correcta: 0,
    explicacion: "La alternativa correcta es «A más de 10 metros, en ambos casos.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20121,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Bajo qué condiciones un estacionamiento reservado puede ser ocupado por cualquier vehículo?",
    opciones: ["Siempre que sea el mismo tipo de vehículo.", "Nunca, está totalmente prohibido.", "Siempre que el conductor del vehículo permanezca en él y lo retire cuando llegue el vehículo que goce de la reserva."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Siempre que el conductor del vehículo permanezca en él y lo retire cuando llegue el vehículo que goce de la reserva.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20122,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D"],
    pregunta: "¿Cómo se deberá estacionar un vehículo cuando la vía está en subida?",
    opciones: ["Con las ruedas delanteras hacia la cuneta.", "Con las ruedas traseras hacia la calzada.", "Con las ruedas delanteras hacia la calzada."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Con las ruedas delanteras hacia la calzada.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20123,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En un accidente, el sólo hecho de la infracción no determina:",
    opciones: ["La gravedad del accidente.", "La responsabilidad civil del infractor.", "Ninguna de las anteriores."],
    correcta: 1,
    explicacion: "La alternativa correcta es «La responsabilidad civil del infractor.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20124,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "No estar atento a las condiciones del tránsito, constituye:",
    opciones: ["Presunción de responsabilidad del conductor.", "Causal de cancelación de licencia.", "Ninguna de las anteriores."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Presunción de responsabilidad del conductor.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20125,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "En todo accidente en que se produzcan daños, el o los participantes estarán obligados a:",
    opciones: ["Huir del sitio del suceso.", "Dar cuenta a la autoridad policial más próxima.", "Llamar al servicio de ambulancias."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Dar cuenta a la autoridad policial más próxima.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20126,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Se presumirá culpabilidad del peatón que cruce la calzada en:",
    opciones: ["El paso de cebra.", "Paso de peatones.", "Lugar prohibido."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Lugar prohibido.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20127,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Se presumirá culpabilidad del peatón cuando pase por:",
    opciones: ["Delante de un vehículo detenido habiendo tránsito libre en la vía respectiva.", "Detrás del vehículo en movimiento.", "Ninguna de las anteriores."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Delante de un vehículo detenido habiendo tránsito libre en la vía respectiva.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20128,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "La luz verde del semáforo indica:",
    opciones: ["Prevención.", "Precaución.", "Paso."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Paso.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20129,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "La luz amarilla del semáforo indica:",
    opciones: ["Prevención.", "Paso.", "Detenerse."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Prevención.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20130,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué indica la luz roja del semáforo?",
    opciones: ["Detención.", "Precaución.", "Paso."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Detención.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20131,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "¿Qué condiciones debe tener el cruce para que el vehículo continúe su marcha, no obstante tenga luz verde al frente?",
    opciones: ["Debe existir previamente luz amarilla.", "Debe existir espacio suficiente para no bloquear el cruce.", "No tener el paso de cebra demarcado."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Debe existir espacio suficiente para no bloquear el cruce.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20132,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Los vehículos que enfrenten un semáforo con luz roja y flecha verde, podrán:",
    opciones: ["Entrar cuidadosamente al cruce sólo para seguir en la dirección indicada en la flecha verde.", "Entrar cuidadosamente al cruce para continuar directo.", "Ninguna de las anteriores."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Entrar cuidadosamente al cruce sólo para seguir en la dirección indicada en la flecha verde.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20133,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "La luz roja intermitente del semáforo indica:",
    opciones: ["Precaución.", "Prevención.", "Ceda el paso."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Ceda el paso.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20134,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "La luz amarilla intermitente del semáforo indica:",
    opciones: ["Pare.", "Peligro.", "Ceda el paso."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Peligro.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20135,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: PARE, curva/zona de curvas, rotonda.",
    opciones: ["Pare, Pavimento resbaladizo, Curva muy cerrada a la derecha.", "Pare, Zona de curvas a la derecha, Proximidad rotonda.", "Pare, Zona de curvas a la izquierda, Proximidad rotonda."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Pare, Zona de curvas a la izquierda, Proximidad rotonda.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20136,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: ceda el paso, viraje/salida, no virar en U.",
    opciones: ["Ceda el paso, Salida de Autopista, Prohibido transitar en el sentido contrario.", "Ceda el paso, Curva a la derecha, No virar en U.", "Fin Restricción, Permitido Virar, No virar en U."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Ceda el paso, Curva a la derecha, No virar en U.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20137,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: no entrar, prohibido estacionar, resalto/pendiente.",
    opciones: ["No entrar, Prohibido Estacionar, Resalto.", "No entrar, Prohibido Estacionar y Detenerse, Pendiente fuerte.", "Tránsito en sentido contrario, Prohibido Detenerse, Resalto."],
    correcta: 0,
    explicacion: "La alternativa correcta es «No entrar, Prohibido Estacionar, Resalto.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20138,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: dirección obligada, camino angosto, zona escolar.",
    opciones: ["Viraje a la derecha, Camino angosto, Niños jugando.", "Dirección Obligada, Puente angosto, Zona de Escuela.", "Dirección Obligada, Camino angosto, Zona de Peatones."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Dirección Obligada, Puente angosto, Zona de Escuela.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20139,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: mantenga su derecha, silencio, velocidad.",
    opciones: ["Mantenga su derecha, Silencio, Velocidad sugerida.", "Pista Solo autos, No Molestar, Velocidad mínima.", "Mantenga su derecha, Silencio, Velocidad máxima."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Mantenga su derecha, Silencio, Velocidad máxima.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20140,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: cruce ferroviario, no adelantar, ancho máximo.",
    opciones: ["Cruce ferroviario a nivel sin barreras, No adelantar, Ancho máximo.", "Cruce ferroviario a nivel con barreras, Prohibido circular vehículos, Ancho máximo.", "Cruce ferroviario a nivel sin barreras, Fin doble vía, Peso máximo."],
    correcta: 0,
    explicacion: "La alternativa correcta es «Cruce ferroviario a nivel sin barreras, No adelantar, Ancho máximo.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20141,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: pavimento resbaladizo, cruce, prohibido estacionar y detenerse.",
    opciones: ["Pavimento resbaladizo, Proximidad Cruce, Prohibido Estacionar.", "Proyección de gravilla, Proximidad Iglesia, Prohibido Estacionar y Detenerse.", "Pavimento resbaladizo, Proximidad Cruce, Prohibido Estacionar y Detenerse."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Pavimento resbaladizo, Proximidad Cruce, Prohibido Estacionar y Detenerse.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20142,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Indique qué significan estas señales: no virar izquierda, ceda el paso, resalto.",
    opciones: ["No virar izquierda, Proximidad de señal \"Ceda el paso\", Badén.", "No entrar, Ceda el Paso, Proximidad de Puente.", "No virar izquierda, Proximidad señal \"Ceda el Paso\", Resalto."],
    correcta: 0,
    explicacion: "La alternativa correcta es «No virar izquierda, Proximidad de señal \"Ceda el paso\", Badén.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20143,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Debe considerarse como velocidad razonable y prudente la que contemple:",
    opciones: ["La temperatura ambiente.", "Sólo el estado del camino.", "Los riesgos y peligros presentes y posibles."],
    correcta: 2,
    explicacion: "La alternativa correcta es «Los riesgos y peligros presentes y posibles.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20144,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "Velocidad razonable y prudente significa:",
    opciones: ["La máxima permitida en la vía.", "Una velocidad que permita controlar el vehículo cuando sea necesario, para evitar accidentes.", "30 km/h."],
    correcta: 1,
    explicacion: "La alternativa correcta es «Una velocidad que permita controlar el vehículo cuando sea necesario, para evitar accidentes.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20145,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2", "D", "E"],
    pregunta: "La velocidad más baja a la que se puede circular es:",
    opciones: ["La que decida el conductor.", "20 km/h.", "La que no impida el desplazamiento normal y adecuado de los demás vehículos."],
    correcta: 2,
    explicacion: "La alternativa correcta es «La que no impida el desplazamiento normal y adecuado de los demás vehículos.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20146,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1"],
    pregunta: "La velocidad máxima de un bus interurbano en una autopista es:",
    opciones: ["100 km/h.", "120 km/h.", "90 km/h."],
    correcta: 0,
    explicacion: "La alternativa correcta es «100 km/h.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20147,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A2"],
    pregunta: "En el caso de un camión de más de 4.000 kg., la velocidad máxima permitida en una carretera es:",
    opciones: ["110 km/h.", "100 km/h.", "90 km/h."],
    correcta: 2,
    explicacion: "La alternativa correcta es «90 km/h.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },
  {
    id: 20148,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 1,
    clases: ["A1", "A2"],
    pregunta: "La velocidad máxima permitida en zonas urbanas para vehículos de carga de peso bruto mayor a 3.860 kg., de transporte escolar y buses es:",
    opciones: ["70 km/h.", "60 km/h.", "50 km/h."],
    correcta: 2,
    explicacion: "La alternativa correcta es «50 km/h.», conforme al cuestionario oficial de CONASET para las clases profesionales A1*, A2*, D y E.",
  },

];

// ── COMPOSICIÓN OFICIAL DEL EXAMEN POR CLASE (CONASET) ──────────────────────
// Número de preguntas por contenido, según tabla oficial.
export const COMPOSICION_PROFESIONAL = {
  A1: { "Conducta Vial": 5, "Mecánica Diésel": 2, "Mecánica Básica": 3, "Conocimientos Legales": 10, total: 20, minCorrectas: 17, maxErroresLegal: 2 },
  A2: { "Conducta Vial": 5, "Mecánica Diésel": 2, "Mecánica Básica": 3, "Conocimientos Legales": 10, total: 20, minCorrectas: 16, maxErroresLegal: 2 },
  D:  { "Conducta Vial": 5, "Mecánica Diésel": 0, "Mecánica Básica": 0, "Conocimientos Legales": 7,  total: 12, minCorrectas: 9,  maxErroresLegal: 2 },
  E:  { "Conducta Vial": 5, "Mecánica Diésel": 0, "Mecánica Básica": 0, "Conocimientos Legales": 5,  total: 10, minCorrectas: 7,  maxErroresLegal: 2 },
};

const shuffle = (arr) => {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

/**
 * Genera un examen oficial para una clase profesional (A1, A2, D o E),
 * respetando la cantidad de preguntas por contenido que exige CONASET.
 */
export function generarExamenProfesional(clase = "A1") {
  const comp = COMPOSICION_PROFESIONAL[clase] || COMPOSICION_PROFESIONAL.A1;
  const pool = PREGUNTAS_PROFESIONAL.filter((p) => p.clases.includes(clase));

  const categorias = ["Conducta Vial", "Mecánica Diésel", "Mecánica Básica", "Conocimientos Legales"];
  let seleccion = [];
  categorias.forEach((cat) => {
    const cantidad = comp[cat] || 0;
    if (cantidad === 0) return;
    const disponibles = shuffle(pool.filter((p) => p.categoria === cat));
    seleccion = seleccion.concat(disponibles.slice(0, cantidad));
  });

  return shuffle(seleccion);
}

/**
 * Evalúa un examen profesional aplicando las dos reglas oficiales de aprobación:
 * 1) mínimo de respuestas correctas para la clase.
 * 2) no más de 2 respuestas incorrectas en "Conocimientos Legales".
 */
export function evaluarExamenProfesional(clase, preguntas, respuestas) {
  const comp = COMPOSICION_PROFESIONAL[clase] || COMPOSICION_PROFESIONAL.A1;
  let correctas = 0;
  let erroresLegal = 0;
  preguntas.forEach((p, i) => {
    const esCorrecta = respuestas[i] === p.correcta;
    if (esCorrecta) correctas++;
    else if (p.categoria === "Conocimientos Legales") erroresLegal++;
  });
  const aprobado = correctas >= comp.minCorrectas && erroresLegal <= comp.maxErroresLegal;
  return { correctas, total: preguntas.length, erroresLegal, minCorrectas: comp.minCorrectas, maxErroresLegal: comp.maxErroresLegal, aprobado };
}
