// ─────────────────────────────────────────────────────────────────────────────
// BANCO DE PREGUNTAS CLASE C — MOTOCICLETAS
// Fuente: Manual del Conductor Chileno — Sección Motocicletas

// ─────────────────────────────────────────────────────────────────────────────

export const PREGUNTAS_MOTO = [

  // ── CONDUCTA VIAL (moto) ────────────────────────────────────────────────────

  {
    id: 1001,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 1,
    pregunta: "¿Por qué parte de la calzada deben circular las motocicletas por norma general?",
    opciones: [
      "Por la mitad izquierda de la calzada.",
      "Por la mitad derecha de la calzada.",
      "Por el centro exacto de la calzada.",
    ],
    correcta: 1,
    explicacion: "Al igual que todo vehículo, la motocicleta debe circular por la mitad derecha de la calzada, salvo excepciones señaladas en la ley.",
  },
  {
    id: 1002,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular entre dos filas de vehículos (filtrar) en un atochamiento?",
    opciones: [
      "Sí, siempre que lo hagan a baja velocidad.",
      "Sí, si los demás vehículos están detenidos.",
      "No, está prohibido circular entre filas de vehículos.",
    ],
    correcta: 2,
    explicacion: "La ley de tránsito chilena prohíbe que las motocicletas circulen entre filas de vehículos (conocido como 'filtrar'). Deben respetar su pista como cualquier vehículo.",
  },
  {
    id: 1003,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "Al circular en una carretera de doble pista por sentido, ¿por qué pista debe circular normalmente una motocicleta?",
    opciones: [
      "Por la pista del lado izquierdo.",
      "Por la pista del lado derecho.",
      "Por cualquier pista indistintamente.",
    ],
    correcta: 1,
    explicacion: "Los vehículos que circulan a velocidad inferior a la máxima, incluidas motocicletas, deben hacerlo por la pista de la derecha, dejando libre la pista izquierda para adelantamientos.",
  },
  {
    id: 1004,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular por las ciclovías?",
    opciones: [
      "Sí, en cualquier momento.",
      "Solo si no hay ciclistas presentes.",
      "No, las ciclovías son exclusivas para ciclistas y otros vehículos no motorizados.",
    ],
    correcta: 2,
    explicacion: "Las ciclovías están destinadas exclusivamente a bicicletas y vehículos no motorizados. Las motocicletas no pueden circular por ellas.",
  },
  {
    id: 1005,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular por la berma de una carretera?",
    opciones: [
      "Sí, si el tráfico en la calzada está muy congestionado.",
      "Sí, cuando circulan lentamente por avería.",
      "No, en ningún caso.",
    ],
    correcta: 2,
    explicacion: "Ningún vehículo puede circular por la berma. Es un espacio reservado para emergencias y peatones, no para circulación de vehículos.",
  },
  {
    id: 1006,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 3,
    pregunta: "Al aproximarse a una curva hacia la izquierda en moto, ¿qué posición debe adoptar el motociclista?",
    opciones: [
      "Mantenerse bien a la derecha de la calzada.",
      "Desplazarse hacia el centro de la calzada para tener mejor visual.",
      "Acercarse a la línea central para acortar la curva.",
    ],
    correcta: 0,
    explicacion: "Al enfrentar una curva hacia la izquierda, el motociclista debe mantenerse bien a la derecha. Esto le da mejor visual y lo ubica en una posición más segura si un vehículo viene en sentido contrario invadiendo su pista.",
  },
  {
    id: 1007,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Cómo debe señalizar un motociclista un viraje a la derecha, usando señas con el brazo?",
    opciones: [
      "Brazo izquierdo extendido horizontalmente.",
      "Brazo izquierdo en ángulo recto hacia arriba.",
      "Brazo izquierdo extendido hacia abajo.",
    ],
    correcta: 1,
    explicacion: "Para indicar un viraje a la derecha con el brazo izquierdo, el motociclista debe levantar el antebrazo formando un ángulo recto hacia arriba (en 'L').",
  },
  {
    id: 1008,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Cómo debe señalizar un motociclista un viraje a la izquierda, usando señas con el brazo?",
    opciones: [
      "Brazo izquierdo extendido horizontalmente.",
      "Brazo izquierdo en ángulo recto hacia arriba.",
      "Brazo izquierdo extendido hacia abajo.",
    ],
    correcta: 0,
    explicacion: "Para indicar un viraje a la izquierda, el motociclista extiende el brazo izquierdo horizontalmente, paralelo al suelo.",
  },
  {
    id: 1009,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Cómo debe señalizar un motociclista una reducción de velocidad, usando señas con el brazo?",
    opciones: [
      "Brazo izquierdo extendido horizontalmente.",
      "Brazo izquierdo en ángulo recto hacia arriba.",
      "Brazo izquierdo extendido hacia abajo.",
    ],
    correcta: 2,
    explicacion: "Para indicar una reducción de velocidad, el motociclista extiende el brazo izquierdo hacia abajo con la palma mirando hacia atrás.",
  },
  {
    id: 1010,
    categoria: "Conducta Vial",
    icono: "road",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular por las autopistas urbanas?",
    opciones: [
      "Sí, siempre.",
      "Solo si circulan a una velocidad superior a 60 km/h.",
      "No, las motocicletas tienen prohibido circular por las autopistas.",
    ],
    correcta: 2,
    explicacion: "Según la legislación chilena, las motocicletas tienen prohibido circular por las autopistas, salvo que exista señalización específica que lo permita.",
  },

  // ── SEGURIDAD VIAL (moto) ───────────────────────────────────────────────────

  {
    id: 1011,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 1,
    pregunta: "¿Es obligatorio el uso de casco para el conductor de una motocicleta en Chile?",
    opciones: [
      "Sí, siempre que circule.",
      "Solo en carreteras y caminos fuera de la ciudad.",
      "No, es optativo.",
    ],
    correcta: 0,
    explicacion: "El uso de casco es obligatorio para el conductor (y pasajero si lo lleva) de una motocicleta en todo momento, tanto en la ciudad como en carretera.",
  },
  {
    id: 1012,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 1,
    puntaje: 2,
    pregunta: "¿Es obligatorio que el pasajero de una motocicleta use casco?",
    opciones: [
      "Sí, siempre.",
      "Solo si viajan en carretera.",
      "No, el casco solo es obligatorio para el conductor.",
    ],
    correcta: 0,
    explicacion: "Tanto el conductor como el pasajero de una motocicleta están obligados a usar casco homologado en todo momento. Su incumplimiento es una infracción grave.",
  },
  {
    id: 1013,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 2,
    pregunta: "¿Por qué se recomienda a los motociclistas usar ropa de colores claros o reflectantes?",
    opciones: [
      "Para identificarse como motociclistas ante las autoridades.",
      "Para ser más visibles a otros conductores y reducir el riesgo de siniestros.",
      "Porque la ley lo exige expresamente.",
    ],
    correcta: 1,
    explicacion: "Los colores claros y reflectantes aumentan la visibilidad del motociclista, especialmente de noche o con poca luz. La falta de visibilidad es una de las principales causas de siniestros con motos.",
  },
  {
    id: 1014,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 2,
    pregunta: "¿Por qué los motociclistas son considerados 'usuarios vulnerables' de la vía?",
    opciones: [
      "Porque sus vehículos son más difíciles de manejar.",
      "Porque tienen menor protección en caso de siniestro.",
      "Porque deben usar rutas especiales.",
    ],
    correcta: 1,
    explicacion: "Los motociclistas son usuarios vulnerables porque ante un siniestro no cuentan con la protección de una carrocería, airbags ni cinturón, lo que aumenta significativamente el riesgo de lesiones graves.",
  },
  {
    id: 1015,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 3,
    pregunta: "Al circular en moto junto a vehículos estacionados, ¿cuál es el principal riesgo que debe considerar el motociclista?",
    opciones: [
      "Que los vehículos estacionados arranquen sin señalizar.",
      "Que se abran puertas de vehículos estacionados repentinamente.",
      "Que los peatones crucen desde la calzada.",
    ],
    correcta: 1,
    explicacion: "El mayor riesgo al circular junto a vehículos estacionados es que se abra una puerta repentinamente ('efecto puerta'). El motociclista debe mantener una distancia lateral segura.",
  },
  {
    id: 1016,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 2,
    pregunta: "¿A qué distancia lateral mínima debe adelantar una motocicleta a un ciclista?",
    opciones: [
      "Al menos 1 metro.",
      "Al menos 1,5 metros.",
      "Al menos 0,5 metros.",
    ],
    correcta: 1,
    explicacion: "La ley de tránsito exige mantener una distancia lateral mínima de 1,5 metros al adelantar a ciclistas. Esto aplica tanto a vehículos como a motocicletas.",
  },
  {
    id: 1017,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 2,
    pregunta: "¿Cuál es uno de los factores más importantes que afecta la estabilidad de una motocicleta en curvas?",
    opciones: [
      "El color de la moto.",
      "La velocidad excesiva al ingresar a la curva.",
      "El tipo de combustible utilizado.",
    ],
    correcta: 1,
    explicacion: "Entrar a una curva a velocidad excesiva es una de las principales causas de pérdida de control de la motocicleta. Se debe reducir la velocidad antes de ingresar y acelerar suavemente al salir.",
  },
  {
    id: 1018,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 3,
    puntaje: 2,
    pregunta: "¿Cómo afecta el alcohol a la conducción de una motocicleta?",
    opciones: [
      "Mejora los reflejos y la confianza del conductor.",
      "Reduce los reflejos, altera la percepción y aumenta el riesgo de siniestros.",
      "Solo afecta si se consume en grandes cantidades.",
    ],
    correcta: 1,
    explicacion: "El alcohol disminuye los reflejos, altera la percepción del riesgo y la coordinación motora. En motocicleta, estos efectos son especialmente peligrosos por la falta de protección del vehículo.",
  },
  {
    id: 1019,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 2,
    pregunta: "¿Qué debe hacer un motociclista cuando va a circular de noche?",
    opciones: [
      "Circular a mayor velocidad para reducir el tiempo de exposición.",
      "Asegurarse de que las luces del vehículo funcionen correctamente y usar ropa reflectante.",
      "Circular solo por carreteras iluminadas.",
    ],
    correcta: 1,
    explicacion: "De noche la visibilidad es reducida. El motociclista debe verificar el funcionamiento de sus luces y usar indumentaria reflectante para ser visible a otros conductores.",
  },
  {
    id: 1020,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 2,
    pregunta: "¿Qué sucede con la distancia de frenado de una motocicleta en pavimento mojado?",
    opciones: [
      "Disminuye porque el agua lubrica los frenos.",
      "No varía con respecto al pavimento seco.",
      "Aumenta porque hay menor adherencia entre el neumático y el pavimento.",
    ],
    correcta: 2,
    explicacion: "En pavimento mojado la adherencia disminuye considerablemente, lo que aumenta la distancia de frenado. El motociclista debe reducir la velocidad y aumentar la distancia de seguimiento.",
  },

  // ── MECÁNICA BÁSICA (moto) ──────────────────────────────────────────────────

  {
    id: 1021,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Con qué frecuencia se recomienda revisar la presión de los neumáticos de una motocicleta?",
    opciones: [
      "Solo cuando se note que está desinflado.",
      "Regularmente, y siempre antes de un viaje largo.",
      "Una vez al año en la revisión técnica.",
    ],
    correcta: 1,
    explicacion: "La presión correcta de los neumáticos es crucial para la seguridad en moto. Debe verificarse regularmente (idealmente cada semana) y siempre antes de viajes largos.",
  },
  {
    id: 1022,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Qué indica un neumático de motocicleta desgastado en el centro de la banda de rodadura?",
    opciones: [
      "Que el neumático está inflado en exceso.",
      "Que el neumático tiene falta de presión.",
      "Que el neumático está inflado correctamente.",
    ],
    correcta: 0,
    explicacion: "Un neumático desgastado en el centro indica que ha estado inflado con exceso de presión. Esto reduce el área de contacto y afecta la adherencia y la estabilidad de la moto.",
  },
  {
    id: 1023,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Qué indica un neumático de motocicleta desgastado en los bordes de la banda de rodadura?",
    opciones: [
      "Que el neumático está inflado en exceso.",
      "Que el neumático tiene falta de presión.",
      "Que la moto fue usada principalmente en curvas.",
    ],
    correcta: 1,
    explicacion: "Un neumático desgastado en los bordes (laterales) indica que circuló con presión insuficiente. La parte central no toca bien el suelo, cargando el desgaste en los bordes.",
  },
  {
    id: 1024,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Qué función cumplen los amortiguadores de una motocicleta?",
    opciones: [
      "Mejorar el rendimiento del motor.",
      "Absorber los impactos y mantener el contacto de los neumáticos con el suelo.",
      "Reducir el consumo de combustible.",
    ],
    correcta: 1,
    explicacion: "Los amortiguadores absorben los golpes e impactos del camino, manteniendo el neumático en contacto con el suelo. Amortiguadores en mal estado reducen el control y la estabilidad.",
  },
  {
    id: 1025,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Qué debe revisar el motociclista antes de iniciar la marcha?",
    opciones: [
      "Solo el nivel de combustible.",
      "Frenos, neumáticos, luces, nivel de aceite y combustible.",
      "Solo el estado de los neumáticos.",
    ],
    correcta: 1,
    explicacion: "Antes de salir, el motociclista debe hacer una revisión completa: frenos, estado y presión de neumáticos, funcionamiento de luces, nivel de aceite y combustible. Se llama revisión previa al viaje.",
  },
  {
    id: 1026,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 3,
    pregunta: "Si la motocicleta comienza a vibrar anormalmente en el manubrio durante la marcha, ¿qué podría indicar?",
    opciones: [
      "Que el motor está funcionando correctamente.",
      "Posible problema en los neumáticos, ruedas o sistema de dirección.",
      "Que la velocidad es demasiado baja.",
    ],
    correcta: 1,
    explicacion: "Una vibración anormal en el manubrio puede indicar problemas en los neumáticos (presión, desgaste), desequilibrio en las ruedas o fallas en la dirección. Se debe detener el vehículo y revisarlo.",
  },
  {
    id: 1027,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Por qué es importante que la cadena de transmisión de la moto esté correctamente tensada y lubricada?",
    opciones: [
      "Para mejorar la estética de la moto.",
      "Para una transmisión eficiente de potencia y evitar roturas que podrían causar siniestros.",
      "Solo para reducir el ruido del motor.",
    ],
    correcta: 1,
    explicacion: "Una cadena mal tensada o sin lubricación puede romperse en marcha, lo que puede causar la pérdida del control de la moto. Debe revisarse periódicamente.",
  },
  {
    id: 1028,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "¿Qué debe hacer el motociclista si nota que los frenos responden con poca eficacia?",
    opciones: [
      "Reducir la velocidad y continuar hasta el destino.",
      "Detenerse de forma segura y revisar o reparar los frenos antes de continuar.",
      "Frenar más fuerte para compensar.",
    ],
    correcta: 1,
    explicacion: "Los frenos son el sistema de seguridad más crítico de la moto. Si no responden correctamente, se debe detener de forma segura de inmediato y no continuar hasta solucionar el problema.",
  },

  // ── REGLAMENTACIÓN (moto) ───────────────────────────────────────────────────

  {
    id: 1029,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 1,
    pregunta: "¿Desde qué edad se puede obtener la licencia de conducir Clase C (motocicleta) en Chile?",
    opciones: [
      "16 años.",
      "17 años.",
      "18 años.",
    ],
    correcta: 2,
    explicacion: "En Chile, la licencia de conducir Clase C para motocicletas se puede obtener a partir de los 18 años, al igual que la Clase B para automóviles.",
  },
  {
    id: 1030,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 1,
    pregunta: "¿Qué autoriza la licencia de conducir Clase C en Chile?",
    opciones: [
      "Conducir automóviles de hasta 9 asientos.",
      "Conducir vehículos motorizados de 2 o 3 ruedas, como motocicletas y motonetas.",
      "Conducir cualquier tipo de vehículo motorizado.",
    ],
    correcta: 1,
    explicacion: "La licencia Clase C autoriza la conducción de vehículos motorizados de dos o tres ruedas, incluyendo motocicletas, motonetas y scooters.",
  },
  {
    id: 1031,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Cuántos pasajeros puede transportar una motocicleta además del conductor?",
    opciones: [
      "Dos pasajeros, si la moto tiene asiento trasero.",
      "Un pasajero, si el vehículo está diseñado para ello y el conductor tiene licencia vigente.",
      "Ninguno, las motocicletas solo permiten al conductor.",
    ],
    correcta: 1,
    explicacion: "Una motocicleta puede transportar un pasajero además del conductor, siempre que el vehículo esté equipado con asiento y reposapiés para el acompañante, y el conductor tenga licencia válida.",
  },
  {
    id: 1032,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Qué documentos debe portar obligatoriamente el conductor de una motocicleta?",
    opciones: [
      "Solo la licencia de conducir.",
      "Licencia de conducir, permiso de circulación, revisión técnica y SOAP.",
      "Solo el permiso de circulación y el SOAP.",
    ],
    correcta: 1,
    explicacion: "El conductor debe portar su licencia de conducir vigente, y el vehículo debe tener permiso de circulación al día, revisión técnica vigente y SOAP (Seguro Obligatorio de Accidentes Personales).",
  },
  {
    id: 1033,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Cuál es la velocidad máxima permitida para motocicletas en zonas urbanas en Chile?",
    opciones: [
      "60 km/h.",
      "50 km/h.",
      "80 km/h.",
    ],
    correcta: 1,
    explicacion: "La velocidad máxima en zonas urbanas es de 50 km/h para todos los vehículos, incluidas las motocicletas, salvo señalización específica que indique otra velocidad.",
  },
  {
    id: 1034,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Cuál es la velocidad máxima permitida para motocicletas en carreteras fuera de zona urbana?",
    opciones: [
      "100 km/h.",
      "120 km/h.",
      "La misma que para automóviles según la señalización.",
    ],
    correcta: 2,
    explicacion: "Las motocicletas deben respetar los mismos límites de velocidad indicados por la señalización de cada vía. No existe un límite diferente para motos respecto a los automóviles en carreteras.",
  },
  {
    id: 1035,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "Conducir una motocicleta bajo la influencia del alcohol con una concentración de 0,5 g/L o más en la sangre se considera:",
    opciones: [
      "Una infracción leve.",
      "Una infracción grave.",
      "Una infracción gravísima.",
    ],
    correcta: 2,
    explicacion: "Conducir bajo la influencia del alcohol (0,3 a 0,79 g/L) es infracción gravísima en moto. El estado de ebriedad (0,8 g/L o más) es además un delito penal.",
  },
  {
    id: 1036,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Qué ocurre si el conductor de una motocicleta es sorprendido sin casco?",
    opciones: [
      "Se le aplica una multa leve.",
      "Se le aplica una multa grave.",
      "Solo se le hace una advertencia.",
    ],
    correcta: 1,
    explicacion: "Conducir sin casco es una infracción grave, sancionada con multa. El casco es un elemento de seguridad obligatorio para motociclistas y sus pasajeros.",
  },
  {
    id: 1037,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Está permitido que una motocicleta lleve carga en la zona trasera?",
    opciones: [
      "Sí, siempre que no supere el ancho del vehículo y no ponga en riesgo la estabilidad.",
      "No, las motocicletas no pueden llevar carga.",
      "Sí, sin ninguna restricción de peso.",
    ],
    correcta: 0,
    explicacion: "Las motocicletas pueden transportar carga en la zona trasera, pero esta no debe superar el ancho del vehículo ni comprometer la estabilidad o visibilidad del conductor.",
  },
  {
    id: 1038,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 3,
    puntaje: 2,
    pregunta: "Un motociclista que no respeta una luz roja de semáforo comete una infracción:",
    opciones: [
      "Leve.",
      "Grave.",
      "Gravísima.",
    ],
    correcta: 2,
    explicacion: "No detenerse ante una luz roja de semáforo es una infracción gravísima para todo conductor, incluidos los motociclistas. Puede implicar suspensión de la licencia.",
  },
  {
    id: 1039,
    categoria: "Reglamentación",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Puede una motocicleta circular con las luces apagadas de día?",
    opciones: [
      "Sí, las luces son obligatorias solo de noche.",
      "No, las motocicletas deben circular siempre con las luces encendidas, incluso de día.",
      "Solo deben encender las luces en túneles.",
    ],
    correcta: 1,
    explicacion: "En Chile, las motocicletas deben circular con las luces encendidas en todo momento, incluso de día. Esto aumenta su visibilidad frente a otros conductores.",
  },

  // ── EL INDIVIDUO EN EL TRÁNSITO ─────────────────────────────────────────────

  {
    id: 1040,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 2,
    pregunta: "¿Qué efecto tiene el cansancio en la conducción de una motocicleta?",
    opciones: [
      "No tiene efecto significativo si el conductor tiene experiencia.",
      "Disminuye los tiempos de reacción y aumenta el riesgo de error.",
      "Mejora la concentración porque el conductor se esfuerza más.",
    ],
    correcta: 1,
    explicacion: "El cansancio reduce los tiempos de reacción, disminuye la atención y aumenta la probabilidad de cometer errores de conducción. En moto, sus consecuencias son más graves.",
  },
  {
    id: 1041,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 2,
    pregunta: "¿Cómo influye el estrés en la conducción de una motocicleta?",
    opciones: [
      "Mejora la concentración y el rendimiento.",
      "No tiene efecto en conductores experimentados.",
      "Puede provocar reacciones desproporcionadas y reducir la capacidad de atención.",
    ],
    correcta: 2,
    explicacion: "Un conductor estresado puede reaccionar de manera desproporcionada ante situaciones de tránsito y tener su campo de atención reducido, lo que aumenta el riesgo de siniestros.",
  },
  {
    id: 1042,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 2,
    pregunta: "Un motociclista que conduce con exceso de confianza en sus habilidades tiende a:",
    opciones: [
      "Conducir de manera más segura por su experiencia.",
      "Tomar riesgos innecesarios y conducir a velocidades excesivas.",
      "Ser más cuidadoso con los demás usuarios de la vía.",
    ],
    correcta: 1,
    explicacion: "El exceso de confianza o la sobreestimación de las propias habilidades lleva a conducir con mayor velocidad, menor distancia de seguridad y menor atención, aumentando el riesgo.",
  },
  {
    id: 1043,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 2,
    pregunta: "¿Qué debe hacer un motociclista si siente que está muy cansado para conducir con seguridad?",
    opciones: [
      "Bajar un poco la velocidad y continuar.",
      "Tomar café para mantenerse despierto y continuar.",
      "Detenerse en un lugar seguro, descansar y reanudar la marcha solo cuando esté descansado.",
    ],
    correcta: 2,
    explicacion: "Ante el cansancio, la única solución segura es detenerse y descansar. El café u otras bebidas estimulantes no eliminan los efectos del cansancio en la conducción.",
  },
  {
    id: 1044,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 2,
    pregunta: "¿Puede un medicamento de venta libre afectar la conducción de una motocicleta?",
    opciones: [
      "No, solo los medicamentos recetados pueden afectarla.",
      "Sí, algunos medicamentos de venta libre pueden causar somnolencia u otros efectos que alteran la conducción.",
      "Solo si se mezclan con alcohol.",
    ],
    correcta: 1,
    explicacion: "Muchos medicamentos de venta libre, como antihistamínicos o analgésicos, pueden causar somnolencia o alterar los reflejos. Se debe leer el prospecto y consultar al farmacéutico.",
  },

  // ── NORMAS DE CIRCULACIÓN (moto) ────────────────────────────────────────────

  {
    id: 1045,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 2,
    pregunta: "Al circular en moto detrás de otro vehículo, ¿qué distancia de seguimiento debe mantener?",
    opciones: [
      "La misma que un automóvil, una distancia razonable y prudente.",
      "5 metros como máximo.",
      "Puede circular muy cerca porque la moto frena mejor.",
    ],
    correcta: 0,
    explicacion: "Las motocicletas deben mantener una distancia de seguimiento razonable y prudente, igual que los automóviles. Aunque frenan bien, en mojado la distancia aumenta significativamente.",
  },
  {
    id: 1046,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 2,
    pregunta: "¿Con cuánta anticipación debe señalizar un motociclista antes de realizar un viraje?",
    opciones: [
      "Con 30 metros de anticipación.",
      "Con 20 metros de anticipación.",
      "Con 10 metros de anticipación.",
    ],
    correcta: 0,
    explicacion: "La ley de tránsito exige señalizar cualquier maniobra de viraje o cambio de pista con al menos 30 metros de anticipación, utilizando indicadores de dirección o señas con el brazo.",
  },
  {
    id: 1047,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 2,
    pregunta: "¿Por qué lado debe adelantar una motocicleta a otro vehículo?",
    opciones: [
      "Por la derecha.",
      "Por la izquierda.",
      "Por cualquier lado si hay espacio suficiente.",
    ],
    correcta: 1,
    explicacion: "Los adelantamientos siempre deben realizarse por la izquierda, salvo en excepciones expresamente señaladas (como vías con pistas exclusivas). Esto aplica a todos los vehículos, incluidas las motos.",
  },
  {
    id: 1048,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 3,
    pregunta: "Al ingresar a una rotonda en moto, ¿a quién debe ceder el paso?",
    opciones: [
      "A los vehículos que ingresan desde la derecha.",
      "A los vehículos que ya circulan dentro de la rotonda.",
      "No debe ceder el paso a nadie.",
    ],
    correcta: 1,
    explicacion: "Al ingresar a una rotonda, siempre se debe ceder el paso a los vehículos que ya están circulando dentro de ella. La motocicleta no tiene ningún privilegio especial.",
  },
  {
    id: 1049,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 2,
    pregunta: "¿Qué debe hacer un motociclista al llegar a un cruce no señalizado donde se enfrentan dos vehículos?",
    opciones: [
      "Acelerar para pasar primero.",
      "Ceder el paso al vehículo que viene desde la derecha.",
      "Ceder el paso al vehículo más grande.",
    ],
    correcta: 1,
    explicacion: "En cruces sin señalización ni semáforo, se aplica la norma de la derecha: se debe ceder el paso al vehículo que viene por la derecha. Esto aplica igualmente a las motocicletas.",
  },
  {
    id: 1050,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 2,
    pregunta: "¿Puede un motociclista estacionar su moto sobre la vereda (acera)?",
    opciones: [
      "Sí, si no obstruye el paso de los peatones.",
      "No, está prohibido estacionar vehículos en la acera.",
      "Sí, las motos pueden estacionarse en la acera porque son pequeñas.",
    ],
    correcta: 1,
    explicacion: "Ningún vehículo puede estacionarse en la acera. Esto obstruye el paso de peatones, incluidas personas con movilidad reducida, y está expresamente prohibido.",
  },
  {
    id: 1051,
    categoria: "Normas de Circulación",
    icono: "traffic-lights",
    dificultad: 3,
    pregunta: "¿Qué debe hacer un motociclista si en una intersección el semáforo está en rojo y un Carabinero le indica que avance?",
    opciones: [
      "Obedecer el semáforo y esperar el verde.",
      "Obedecer la instrucción del Carabinero.",
      "Esperar a que otros vehículos avancen primero.",
    ],
    correcta: 1,
    explicacion: "Las instrucciones del personal de Carabineros tienen preferencia sobre las señales de tránsito, incluidos los semáforos. Si un Carabinero indica avanzar, se debe obedecer.",
  },

  // ── CONVIVENCIA VIAL ────────────────────────────────────────────────────────

  {
    id: 1052,
    categoria: "Convivencia Vial",
    icono: "heart-handshake",
    dificultad: 2,
    pregunta: "¿Por qué es importante que los motociclistas respeten especialmente el espacio de los ciclistas?",
    opciones: [
      "Porque los ciclistas tienen prioridad absoluta en toda la vía.",
      "Porque los ciclistas son usuarios vulnerables con menor protección ante un siniestro.",
      "Porque la ley lo exige solo en zonas urbanas.",
    ],
    correcta: 1,
    explicacion: "Los ciclistas, al igual que los peatones, son usuarios vulnerables. Ante un siniestro con una moto, la diferencia de masa y velocidad puede causarles lesiones graves.",
  },
  {
    id: 1053,
    categoria: "Convivencia Vial",
    icono: "heart-handshake",
    dificultad: 2,
    pregunta: "Al acercarse a un paso de cebra donde hay un peatón esperando cruzar, ¿qué debe hacer el motociclista?",
    opciones: [
      "Acelerar para cruzar antes que el peatón empiece.",
      "Ceder el paso al peatón y esperar a que cruce.",
      "Tocar la bocina para avisar al peatón.",
    ],
    correcta: 1,
    explicacion: "El conductor debe ceder el paso a los peatones en los pasos de cebra. Esto aplica tanto si el peatón está cruzando como si está esperando para cruzar.",
  },
  {
    id: 1054,
    categoria: "Convivencia Vial",
    icono: "heart-handshake",
    dificultad: 2,
    pregunta: "¿Cuándo puede el conductor de una motocicleta usar la bocina?",
    opciones: [
      "Para hacer notar su presencia a un amigo.",
      "Para apurar al vehículo que va delante.",
      "Solo para prevenir la ocurrencia de un siniestro.",
    ],
    correcta: 2,
    explicacion: "La bocina solo debe usarse para prevenir un siniestro. Usarla para apurar a otros conductores o llamar la atención de personas es una infracción.",
  },
  {
    id: 1055,
    categoria: "Convivencia Vial",
    icono: "heart-handshake",
    dificultad: 2,
    pregunta: "Si el motociclista está involucrado en un siniestro con personas lesionadas, ¿qué debe hacer?",
    opciones: [
      "Continuar si el accidente fue culpa de otro.",
      "Detenerse, prestar ayuda y avisar a Carabineros de inmediato.",
      "Llamar a Carabineros desde el lugar pero no es necesario detenerse.",
    ],
    correcta: 1,
    explicacion: "Ante un siniestro con lesionados, el conductor está obligado a detenerse, prestar la ayuda posible e informar inmediatamente a Carabineros. Abandonar el lugar es un delito.",
  },

  // ── CONDUCCIÓN EFICIENTE ────────────────────────────────────────────────────

  {
    id: 1056,
    categoria: "Conducción Eficiente",
    icono: "gas-station",
    dificultad: 2,
    pregunta: "¿Qué técnica de conducción permite reducir el consumo de combustible en una motocicleta?",
    opciones: [
      "Acelerar fuertemente y frenar con frecuencia.",
      "Anticipar el tráfico, mantener velocidad constante y evitar aceleraciones bruscas.",
      "Circular siempre en la marcha más baja.",
    ],
    correcta: 1,
    explicacion: "Una conducción suave y anticipativa, manteniendo velocidad constante y usando adecuadamente las marchas, reduce significativamente el consumo de combustible y el desgaste del vehículo.",
  },
  {
    id: 1057,
    categoria: "Conducción Eficiente",
    icono: "gas-station",
    dificultad: 2,
    pregunta: "¿Por qué es importante el mantenimiento preventivo de la motocicleta?",
    opciones: [
      "Solo para cumplir con la revisión técnica.",
      "Para garantizar la seguridad, prolongar la vida útil del vehículo y reducir el consumo.",
      "Solo para mejorar la estética.",
    ],
    correcta: 1,
    explicacion: "El mantenimiento preventivo regular asegura que todos los sistemas de la moto funcionen correctamente, lo que es fundamental para la seguridad, la eficiencia y la durabilidad del vehículo.",
  },

  // ── NUEVAS PREGUNTAS (importadas 2026-06-29) ──────────────────────────────

  {
    id: 1058,
    categoria: "Conducta Vial",
    icono: "motorbike",
    dificultad: 1,
    pregunta: "¿Cuál es el mayor riesgo a la hora de conducir una motocicleta?",
    opciones: [
      "La inexperiencia, la imprudencia",
      "La inexperiencia",
      "Las drogas",
    ],
    correcta: 0,
    explicacion: "El mayor riesgo combina la inexperiencia con la imprudencia: ambos factores juntos aumentan considerablemente la probabilidad de un siniestro en motocicleta.",
  },
  {
    id: 1059,
    categoria: "Conducta Vial",
    icono: "search",
    dificultad: 1,
    pregunta: "Mientras conduce, lo más apropiado y seguro es mirar regularmente por los espejos retrovisores:",
    opciones: [
      "Varias veces en un minuto.",
      "Sólo si desea cambiar de pista y adelantar.",
      "Cada 5 minutos más o menos.",
    ],
    correcta: 0,
    explicacion: "Se debe revisar los espejos retrovisores con frecuencia, varias veces por minuto, para mantener una visión constante del entorno y no solo al momento de maniobrar.",
  },
  {
    id: 1060,
    categoria: "Conducta Vial",
    icono: "motorbike",
    dificultad: 2,
    pregunta: "Las señales manuales que se realicen por el líder de un grupo de motociclistas deben ser acordadas previamente y después repetidas por los demás.",
    opciones: [
      "Verdadero",
      "Falso",
    ],
    correcta: 0,
    explicacion: "Es verdadero: al circular en grupo, las señales manuales del líder deben acordarse de antemano y ser repetidas por el resto de los motociclistas, para mantener una comunicación clara entre todos.",
  },
  {
    id: 1061,
    categoria: "Convivencia Vial",
    icono: "traffic-lights",
    dificultad: 2,
    pregunta: "Un peatón ESTÁ ATRAVESANDO un cruce regulado por un semáforo. El semáforo cambia a rojo y aún no termina de cruzar. ¿Qué debe hacer el peatón?",
    opciones: [
      "Devolverse a la acera",
      "Detenerse y esperar",
      "Continuar el cruce",
    ],
    correcta: 2,
    explicacion: "Si el peatón ya está cruzando cuando cambia la luz, debe continuar y terminar de cruzar lo antes posible, ya que devolverse o detenerse a mitad de la calzada es más peligroso.",
  },
  {
    id: 1062,
    categoria: "Mecánica Básica",
    icono: "settings",
    dificultad: 2,
    pregunta: "Al desenganchar el motor (poner el embrague o punto muerto), usted NO pierde el dominio del vehículo:",
    opciones: [
      "Verdadero",
      "Falso",
    ],
    correcta: 1,
    explicacion: "Es falso: al desenganchar el motor se pierde el frenado por motor y parte del control sobre el vehículo, por lo que esta práctica reduce la capacidad de reacción del conductor.",
  },
  {
    id: 1063,
    categoria: "Normas de Circulación",
    icono: "corner-up-right",
    dificultad: 2,
    pregunta: "¿Cuáles situaciones son correctas tratándose de sobrepasos por la derecha?",
    opciones: [
      "Cuando sobrepasa a un vehículo que está virando a la izquierda",
      "Cuando el vehículo alcanzado esté realizando o esté a punto de efectuar un viraje a la derecha",
      "Cuando el vehículo alcanzado esté realizando o esté a punto de efectuar un viraje a la izquierda o cuando circule por una vía urbana con tres o más pistas de circulación con un mismo sentido de tránsito",
    ],
    correcta: 2,
    explicacion: "El sobrepaso por la derecha solo es válido cuando el vehículo alcanzado va a virar a la izquierda, o en vías urbanas con tres o más pistas en el mismo sentido.",
  },
  {
    id: 1064,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 1,
    pregunta: "Para conducir con seguridad, lo más decisivo es:",
    opciones: [
      "Leyes claras en todas las situaciones.",
      "Leyes rígidas y vigilancia.",
      "El sentido común, buen juicio y responsabilidad.",
    ],
    correcta: 2,
    explicacion: "Por sobre las leyes y la fiscalización, lo más decisivo para conducir con seguridad es el sentido común, el buen juicio y la responsabilidad personal del conductor.",
  },
  {
    id: 1065,
    categoria: "Normas de Circulación",
    icono: "corner-up-left",
    dificultad: 2,
    pregunta: "Un conductor va por una calle de doble sentido de tránsito. ¿Dónde se ubica para virar a la izquierda?",
    opciones: [
      "A la derecha de la línea del centro de la calzada",
      "Al centro de la pista donde va transitando",
      "A la izquierda de la línea del centro de la calzada",
    ],
    correcta: 0,
    explicacion: "Para virar a la izquierda en una calle de doble sentido, el conductor debe ubicarse a la derecha de la línea del centro de la calzada antes de efectuar el viraje.",
  },
  {
    id: 1066,
    categoria: "Conducta Vial",
    icono: "ruler",
    dificultad: 3,
    pregunta: "Si su distancia de reacción es de 10 metros y la de frenado es de 20 metros, dando una distancia total de detención de 30 metros, ¿cuál sería su nueva distancia de detención si duplica su velocidad en las mismas condiciones de calzada?",
    opciones: [
      "52 metros",
      "100 metros",
      "80 metros",
    ],
    correcta: 1,
    explicacion: "La distancia de reacción es proporcional a la velocidad (se duplica a 20 m), pero la distancia de frenado es proporcional al cuadrado de la velocidad (se cuadruplica a 80 m). Sumadas: 20 + 80 = 100 metros.",
  },
  {
    id: 1067,
    categoria: "El Individuo en el Tránsito",
    icono: "pill",
    dificultad: 1,
    pregunta: "El doctor le ha recetado unos remedios. ¿Cuál es la principal razón por la que debe consultarle si puede conducir o no?",
    opciones: [
      "Porque las medicinas pueden afectar a su visión.",
      "Porque algunas medicinas pueden hacer que sus reacciones sean más lentas.",
      "Porque las drogas influyen en su conducción al hacer más rápidas sus reacciones.",
    ],
    correcta: 1,
    explicacion: "La principal razón es que ciertos medicamentos pueden hacer más lentas las reacciones del conductor, afectando su capacidad de respuesta ante imprevistos.",
  },
  {
    id: 1068,
    categoria: "Convivencia Vial",
    icono: "horse",
    dificultad: 2,
    pregunta: "Usted va conduciendo por un camino de doble tránsito cuando se encuentra con personas que van a caballo delante suyo. ¿Qué es lo primero que usted debería hacer?",
    opciones: [
      "Acelerar alrededor de ellos.",
      "Señalizar hacia la izquierda.",
      "Prepararse para reducir la velocidad.",
    ],
    correcta: 2,
    explicacion: "Lo primero es prepararse para reducir la velocidad, dado que los animales pueden comportarse de forma impredecible y se necesita tiempo y espacio para maniobrar con seguridad.",
  },
  {
    id: 1069,
    categoria: "Convivencia Vial",
    icono: "horse",
    dificultad: 2,
    pregunta: "¿Cómo debería usted adelantar a personas que van a caballo?",
    opciones: [
      "La velocidad no es importante, pero sí el dejar suficiente espacio lateral.",
      "Conduciendo lentamente y dejando bastante espacio lateral.",
      "Pasando cerca de ellas y adelantándolas lo antes posible.",
    ],
    correcta: 1,
    explicacion: "Se debe adelantar conduciendo lentamente y dejando bastante espacio lateral, ya que los caballos pueden asustarse con el ruido o la cercanía de los vehículos.",
  },
  {
    id: 1070,
    categoria: "El Individuo en el Tránsito",
    icono: "pill",
    dificultad: 2,
    pregunta: "El mayor riesgo de conducir habiendo consumido drogas está dado por el hecho de que todas ellas actúan sobre:",
    opciones: [
      "El corazón",
      "El cerebro",
      "Las piernas",
    ],
    correcta: 1,
    explicacion: "Todas las drogas, sin excepción, actúan sobre el cerebro, alterando la percepción, el juicio, los reflejos y la capacidad de tomar decisiones al conducir.",
  },
  {
    id: 1071,
    categoria: "Normas de Circulación",
    icono: "train",
    dificultad: 2,
    pregunta: "En un cruce ferroviario, ¿cuál afirmación es FALSA?",
    opciones: [
      "No adelante a menos de 200 metros de él",
      "Ninguna de las mencionadas",
      "No estacionar a menos de 20 metros de él",
    ],
    correcta: 1,
    explicacion: "Ambas afirmaciones (no adelantar a menos de 200 metros y no estacionar a menos de 20 metros de un cruce ferroviario) son correctas, por lo que ninguna de ellas es falsa.",
  },
  {
    id: 1072,
    categoria: "Conducta Vial",
    icono: "building-skyscraper",
    dificultad: 2,
    pregunta: "Usted va conduciendo de noche por una carretera urbana, cerca de otros vehículos que van delante suyo. ¿Qué luces debería mantener encendidas?",
    opciones: [
      "Las luces bajas.",
      "Las luces altas.",
      "Las neblineras delanteras.",
    ],
    correcta: 0,
    explicacion: "Cuando se circula cerca de otros vehículos por delante, se deben usar las luces bajas para no encandilar al conductor que va adelante a través de los espejos.",
  },
  {
    id: 1073,
    categoria: "Reglamentación",
    icono: "firetruck",
    dificultad: 2,
    pregunta: "¿A cuántos metros de un grifo para incendio y de un cuartel de bomberos se puede estacionar un vehículo?",
    opciones: [
      "A menos de 6 metros y 5 metros, respectivamente.",
      "A más de 5 metros y 10 metros, respectivamente.",
      "A más de un metro y 3 metros, respectivamente.",
    ],
    correcta: 1,
    explicacion: "Está permitido estacionar solo a más de 5 metros de un grifo de incendio y a más de 10 metros de un cuartel de bomberos, para no obstaculizar su uso en una emergencia.",
  },
  {
    id: 1074,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 1,
    pregunta: "¿Qué tipo de casco es mayormente recomendable?",
    opciones: [
      "Militares",
      "Integrales",
      "Motocross",
      "Modulares",
    ],
    correcta: 1,
    explicacion: "El casco integral es el más recomendable porque cubre completamente la cabeza y el rostro, ofreciendo la mayor protección ante un siniestro.",
  },
  {
    id: 1075,
    categoria: "Mecánica Básica",
    icono: "steering-wheel",
    dificultad: 2,
    pregunta: "Es esencial que la presión de los neumáticos sea chequeada regularmente. ¿Cuándo se debe hacer esto?",
    opciones: [
      "Cuando los neumáticos están calientes.",
      "Cuando los neumáticos están fríos.",
      "Después de un viaje largo.",
    ],
    correcta: 1,
    explicacion: "La presión de los neumáticos debe revisarse cuando están fríos, ya que el calor generado por la circulación aumenta la presión y entrega una lectura incorrecta.",
  },
  {
    id: 1076,
    categoria: "Mecánica Básica",
    icono: "settings",
    dificultad: 2,
    pregunta: "Conducir sin retirar totalmente el pie del pedal de embrague produce:",
    opciones: [
      "Desgaste prematuro en la balata del embrague.",
      "Desgaste en el motor del vehículo.",
      "Menor fuerza en el motor.",
    ],
    correcta: 0,
    explicacion: "Mantener el pie parcialmente sobre el pedal de embrague genera un patinaje constante del disco, lo que produce un desgaste prematuro de la balata del embrague.",
  },
  {
    id: 1077,
    categoria: "Mecánica Básica",
    icono: "temperature",
    dificultad: 2,
    pregunta: "Con respecto al funcionamiento del vehículo, ¿qué afirmación es verdadera?",
    opciones: [
      "Una batería mal cargada hace que el vehículo tenga un mejor arranque.",
      "Cuando el motor está siendo lubricado se enciende una luz testigo en el panel de instrumentos del vehículo.",
      "Casi siempre, el motor se enfría con un líquido refrigerante que circula por canales en el bloque del motor.",
    ],
    correcta: 2,
    explicacion: "Los motores de combustión normalmente se enfrían mediante un líquido refrigerante que circula por canales dentro del bloque del motor, disipando el calor generado.",
  },
  {
    id: 1078,
    categoria: "Convivencia Vial",
    icono: "user",
    dificultad: 2,
    pregunta: "Estadísticamente, la mayor cantidad de niños atropellados son varones entre:",
    opciones: [
      "4 y 10 años, que irrumpen sorpresivamente en la calzada.",
      "8 y 10 años, que irrumpen sorpresivamente en la calzada.",
      "4 y 8 años, que irrumpen sorpresivamente en la calzada.",
    ],
    correcta: 2,
    explicacion: "Las estadísticas de siniestros viales indican que la mayoría de los niños atropellados son varones entre 4 y 8 años, que irrumpen de forma sorpresiva en la calzada.",
  },
  {
    id: 1079,
    categoria: "Conducta Vial",
    icono: "car",
    dificultad: 2,
    pregunta: "¿Cuál o cuáles de las siguientes situaciones podrían ser la causa de que un conductor choque por detrás a otro vehículo? I) Falta de atención al tránsito II) Conducir muy cerca del vehículo que va adelante III) Una frenada violenta y sorpresiva del vehículo que va adelante",
    opciones: [
      "I, II y III.",
      "Sólo I",
      "Sólo II",
    ],
    correcta: 0,
    explicacion: "Las tres situaciones (falta de atención, conducir muy cerca del vehículo de adelante, y una frenada violenta y sorpresiva) son causas frecuentes de las colisiones por detrás.",
  },
  {
    id: 1080,
    categoria: "Conducta Vial",
    icono: "arrows-left-right",
    dificultad: 3,
    pregunta: "Una persona conduce durante largo rato por una calzada recta en muy buen estado y con poco tránsito en contra. En estas circunstancias, el conductor encuentra un vehículo al que desea adelantar. Respecto a esta acción, ¿cuál de las siguientes afirmaciones es VERDADERA?",
    opciones: [
      "Adelantar en esta situación puede ser peligroso ya que el conductor puede subestimar la velocidad del tránsito que viene en contra",
      "Adelantar en esta situación no es recomendable, ya que puede cruzarse un peatón de manera sorpresiva",
      "Adelantar en esta situación es siempre correcto y no implica riesgo alguno",
    ],
    correcta: 0,
    explicacion: "Tras conducir largo rato en una vía recta y despejada, el conductor puede subestimar la velocidad real de los vehículos que vienen en sentido contrario, lo que hace riesgoso el adelantamiento.",
  },
  {
    id: 1081,
    categoria: "Convivencia Vial",
    icono: "walk",
    dificultad: 1,
    pregunta: "¿Qué debemos hacer cuando nos aproximamos a un cruce peatonal marcado en la vía?",
    opciones: [
      "Reducir la velocidad",
      "Tocar la bocina para alertar al peatón que no se baje de la vereda",
      "Acelerar para pasar más rápido",
    ],
    correcta: 0,
    explicacion: "Al aproximarse a un cruce peatonal marcado siempre se debe reducir la velocidad, dando prioridad y seguridad a quienes puedan cruzar.",
  },
  {
    id: 1082,
    categoria: "El Individuo en el Tránsito",
    icono: "pill",
    dificultad: 3,
    pregunta: "Con respecto al éxtasis, indique las afirmaciones verdaderas: I) Es posible experimentar ilusiones ópticas, como flashes en la periferia del campo visual, lo que podría ocasionar la acción de maniobras evasivas bruscas y peligrosas. II) Períodos de mayor sensibilidad a la luz. III) Dificultad para mantener la concentración, episodios de depresión o ansiedad y, una vez que desaparecen los síntomas, períodos de agotamiento físico y mental.",
    opciones: [
      "Sólo I.",
      "I, II y III.",
      "Sólo II y III.",
    ],
    correcta: 1,
    explicacion: "El consumo de éxtasis puede provocar las tres consecuencias descritas: ilusiones ópticas, mayor sensibilidad a la luz, y dificultad de concentración con posterior agotamiento físico y mental.",
  },
  {
    id: 1083,
    categoria: "El Individuo en el Tránsito",
    icono: "zzz",
    dificultad: 2,
    pregunta: "¿Qué situación puede favorecer la aparición de la fatiga al volante?",
    opciones: [
      "Circular por una vía con poco tráfico",
      "Buena ventilación o bajas temperaturas al interior del vehículo",
      "Conducir de noche o con condiciones climatológicas adversas",
    ],
    correcta: 2,
    explicacion: "Conducir de noche o bajo condiciones climáticas adversas exige mayor esfuerzo visual y de concentración, lo que favorece la aparición de la fatiga al volante.",
  },
  {
    id: 1084,
    categoria: "Convivencia Vial",
    icono: "motorbike",
    dificultad: 1,
    pregunta: "Usted desea adelantar a un motociclista que va delante suyo, ¿qué hace usted?",
    opciones: [
      "Pasa cerca de él y lo más rápido posible.",
      "Trata de pasarlo en una curva.",
      "Le da tanto espacio lateral como le daría a un automóvil.",
    ],
    correcta: 2,
    explicacion: "Al adelantar a un motociclista se debe dar el mismo espacio lateral que se le daría a un automóvil, respetando su espacio y evitando maniobras que puedan desestabilizarlo.",
  },
  {
    id: 1085,
    categoria: "Conducción Eficiente",
    icono: "gas-station",
    dificultad: 1,
    pregunta: "¿Influye el comportamiento del conductor en el consumo de combustible de un vehículo?",
    opciones: [
      "No, el consumo depende únicamente de la cilindrada del motor.",
      "Sí.",
      "No, el consumo sólo depende de la carga del vehículo.",
    ],
    correcta: 1,
    explicacion: "El comportamiento del conductor (aceleraciones bruscas, velocidad, anticipación) influye directamente en el consumo de combustible, además de otros factores del vehículo.",
  },
  {
    id: 1086,
    categoria: "Mecánica Básica",
    icono: "steering-wheel",
    dificultad: 2,
    pregunta: "Cuando un neumático delantero tiene baja presión:",
    opciones: [
      "La dirección del vehículo tiende hacia un lado.",
      "Se sobrecalienta el motor.",
      "El motor pierde potencia.",
    ],
    correcta: 0,
    explicacion: "Una baja presión en un neumático delantero hace que la dirección del vehículo tienda hacia el lado del neumático afectado, dificultando el control de la trayectoria.",
  },
  {
    id: 1087,
    categoria: "Reglamentación",
    icono: "building-skyscraper",
    dificultad: 2,
    pregunta: "Cuando siendo de noche estacione en una vía sin alumbrado público o cuando las condiciones de visibilidad sean deficientes, asegúrese de poder ser visto por los demás conductores manteniendo siempre encendidas sus luces de estacionamiento.",
    opciones: [
      "Verdadero",
      "Falso",
    ],
    correcta: 0,
    explicacion: "Es verdadero: en condiciones de baja visibilidad o sin alumbrado público, se deben mantener encendidas las luces de estacionamiento para que el vehículo sea visible a otros conductores.",
  },
  {
    id: 1088,
    categoria: "Mecánica Básica",
    icono: "settings",
    dificultad: 1,
    pregunta: "La función del embrague es:",
    opciones: [
      "Conectar y desconectar \"la fuerza\" del motor a la caja de velocidades.",
      "Darle fuerza al motor del vehículo.",
      "Frenar el motor del vehículo.",
    ],
    correcta: 0,
    explicacion: "El embrague permite conectar y desconectar la fuerza del motor respecto a la caja de velocidades, lo que posibilita cambiar de marcha o detener el vehículo sin apagar el motor.",
  },

  // ── NUEVAS PREGUNTAS CLASE C (importadas 2026-06-30) ─────────────────────

  {
    id: 1089,
    categoria: "Seguridad Vial",
    icono: "helmet",
    dificultad: 1,
    pregunta: "¿Por qué es recomendable que el casco tenga orificios?",
    opciones: [
      "Para evitar vibraciones.",
      "Para ventilar la cabeza y reducir la sudoración.",
      "Para reducir el peso del casco.",
    ],
    correcta: 1,
    explicacion: "Los orificios de ventilación del casco permiten la circulación de aire, reduciendo la sudoración y manteniendo la cabeza fresca, lo que contribuye a la comodidad y concentración del conductor.",
  },
  {
    id: 1090,
    categoria: "Conducta Vial",
    icono: "ruler",
    dificultad: 2,
    pregunta: "La distancia de frenado es la distancia que recorre un vehículo desde que se acciona el freno hasta que se detiene completamente. ¿Qué sucede con la distancia de frenado si se duplica la velocidad?",
    opciones: [
      "Se duplica.",
      "Se cuadruplica.",
      "Se triplica.",
    ],
    correcta: 1,
    explicacion: "La distancia de frenado es proporcional al cuadrado de la velocidad. Al duplicar la velocidad, la distancia de frenado se cuadruplica (no simplemente se duplica).",
  },
  {
    id: 1091,
    categoria: "Convivencia Vial",
    icono: "motorbike",
    dificultad: 2,
    pregunta: "Los peatones, los ciclistas y los conductores de vehículos de motor de dos ruedas son los usuarios de la vía más vulnerables, ¿Por qué?",
    opciones: [
      "Porque son los que menos respetan las normas de tránsito.",
      "Porque carecen de estructura protectora a su alrededor.",
      "Porque son los que viajan a mayor velocidad.",
    ],
    correcta: 1,
    explicacion: "Los usuarios vulnerables (peatones, ciclistas y motociclistas) carecen de una estructura metálica protectora a su alrededor, lo que los expone directamente a los impactos y hace que sus lesiones sean más graves.",
  },
  {
    id: 1092,
    categoria: "Conducta Vial",
    icono: "bolt",
    dificultad: 2,
    pregunta: "Un conductor al encontrar un imprevisto en su conducción, ¿alrededor de cuánto es el tiempo de reacción?",
    opciones: [
      "0,1 segundos.",
      "3/4 de segundo.",
      "2 segundos.",
    ],
    correcta: 1,
    explicacion: "El tiempo de reacción promedio de un conductor ante un imprevisto es de aproximadamente 3/4 de segundo (0,75 s). Durante ese tiempo el vehículo sigue avanzando sin que el conductor haya actuado.",
  },
  {
    id: 1093,
    categoria: "Conocimientos Legales",
    icono: "scale",
    dificultad: 2,
    pregunta: "La Ley Emilia, ¿sanciona con cárcel efectiva de al menos un año a los conductores que causen lesiones graves o la muerte de otra persona mientras conducen bajo la influencia del alcohol o las drogas?",
    opciones: [
      "Verdadero",
      "Falso",
    ],
    correcta: 0,
    explicacion: "Es verdadero: la Ley Emilia (Ley 20.770) establece pena de cárcel efectiva de al menos un año para conductores que, bajo los efectos del alcohol o drogas, causen lesiones graves gravísimas o la muerte de otra persona.",
  },
  {
    id: 1094,
    categoria: "Conducta Vial",
    icono: "ruler",
    dificultad: 2,
    pregunta: "Si el estado de los frenos y neumáticos no es óptimo en su vehículo, la distancia de detención:",
    opciones: [
      "Disminuye.",
      "No varía.",
      "Aumenta.",
    ],
    correcta: 2,
    explicacion: "El mal estado de frenos y neumáticos reduce la capacidad de frenado, aumentando la distancia necesaria para detener el vehículo y elevando el riesgo de siniestro.",
  },
  {
    id: 1095,
    categoria: "Conocimientos Legales",
    icono: "clipboard-list",
    dificultad: 2,
    pregunta: "¿Cómo se clasifica la infracción de desobedecer las señales u órdenes de Carabineros?",
    opciones: [
      "Infracción leve.",
      "Infracción gravísima.",
      "Infracción menos grave.",
    ],
    correcta: 1,
    explicacion: "Desobedecer las señales u órdenes de Carabineros es una infracción gravísima según la Ley de Tránsito chilena, lo que conlleva las sanciones más severas del sistema de multas.",
  },
  {
    id: 1096,
    categoria: "Conducta Vial",
    icono: "motorbike",
    dificultad: 2,
    pregunta: "Si el vehículo no cuenta con luces de freno operativas y se necesita avisar al conductor de atrás que usted está frenando, ¿qué debería hacer?",
    opciones: [
      "Frenar y acelerar repetidamente para que el vehículo de atrás note que usted está reduciendo la velocidad.",
      "Hacer señas con la mano indicando que va a frenar.",
      "Tocar la bocina.",
    ],
    correcta: 1,
    explicacion: "Sin luces de freno operativas, la forma de advertir al conductor de atrás es realizar señas con la mano indicando que se va a reducir la velocidad, conforme a las señales manuales establecidas.",
  },
  {
    id: 1097,
    categoria: "Señalización",
    icono: "ban",
    dificultad: 2,
    pregunta: "¿Cuál descripción corresponde a las señales de prohibición?",
    opciones: [
      "Advierten a los usuarios sobre los riesgos y/o situaciones imprevistas presentes en la vía o en su entorno. Estos peligros pueden presentarse de forma permanente o temporal.",
      "Se usan para prohibir o limitar el tránsito de ciertos tipos de vehículos o determinados movimientos.",
      "Se usan para restringir o limitar el tránsito debido a características particulares de la vía. Las señales de velocidad máxima pueden agruparse en un mismo panel para distintos tipos de vehículos.",
    ],
    correcta: 1,
    explicacion: "Las señales de prohibición se usan para prohibir o limitar el tránsito de ciertos tipos de vehículos o determinados movimientos. Las de advertencia avisan peligros, y las de restricción limitan por características de la vía.",
  },
  {
    id: 1098,
    categoria: "Conducta Vial",
    icono: "brain",
    dificultad: 1,
    pregunta: "¿Qué medidas de precaución NO son necesarias mientras usted conduce?",
    opciones: [
      "Mantener siempre los ojos en el camino.",
      "Ajustar constantemente el espejo retrovisor mientras conduce.",
      "Mantener ambas manos en el volante.",
    ],
    correcta: 1,
    explicacion: "Los espejos deben ajustarse antes de iniciar la marcha, no mientras se conduce. Ajustarlos en movimiento distrae la atención y aumenta el riesgo de siniestro.",
  },
  {
    id: 1099,
    categoria: "Mecánica Básica",
    icono: "tool",
    dificultad: 2,
    pregunta: "El que los frenos rocen puede deberse a...",
    opciones: [
      "Exceso de líquido de frenos.",
      "Pastillas de freno desgastadas o mal ajustadas.",
      "Neumáticos con baja presión.",
    ],
    correcta: 1,
    explicacion: "El roce de los frenos es síntoma típico de pastillas desgastadas o mal ajustadas, lo que reduce la eficacia del frenado y puede dañar los discos si no se corrige a tiempo.",
  },
  {
    id: 1100,
    categoria: "Conducta Vial",
    icono: "gas-station",
    dificultad: 2,
    pregunta: "De pronto, el aire de la cabina se impregna con aroma a bencina mientras el vehículo está en movimiento. ¿Qué debe hacer?",
    opciones: [
      "Continuar conduciendo y ventilando la cabina con las ventanas abiertas.",
      "Detener el vehículo de forma segura, apagar el motor, salir del vehículo y alejarse de él.",
      "Acelerar para llegar más rápido a un taller.",
    ],
    correcta: 1,
    explicacion: "El olor a bencina dentro del vehículo puede indicar una fuga de combustible con riesgo de incendio. Se debe detener el vehículo en forma segura, apagar el motor, evacuar y alejarse.",
  },
  {
    id: 1101,
    categoria: "Conducta Vial",
    icono: "eye",
    dificultad: 2,
    pregunta: "¿Cómo difiere la visión periférica entre conductores con experiencia y conductores sin experiencia?",
    opciones: [
      "Los conductores sin experiencia tienen mayor visión periférica porque están más atentos.",
      "No existe diferencia en la visión periférica entre conductores con y sin experiencia.",
      "Los conductores con experiencia tienen mayor visión periférica porque aprenden a distribuir mejor la atención visual.",
    ],
    correcta: 2,
    explicacion: "La experiencia permite al conductor distribuir mejor su atención visual, ampliando efectivamente su visión periférica al no necesitar concentrarse tanto en cada acción básica de conducción.",
  },
  {
    id: 1102,
    categoria: "Conducta Vial",
    icono: "snowflake",
    dificultad: 2,
    pregunta: "Conducir en forma segura cuando la calzada está con hielo es:",
    opciones: [
      "Fácil si se tienen neumáticos de invierno.",
      "Imposible con cualquier tipo de neumático.",
      "Muy difícil, incluso con neumáticos de invierno.",
    ],
    correcta: 2,
    explicacion: "El hielo en la calzada reduce drásticamente la adherencia de los neumáticos. Incluso con neumáticos de invierno, conducir sobre hielo es muy difícil y requiere velocidades muy bajas y maniobras extremadamente suaves.",
  },
  {
    id: 1103,
    categoria: "Conocimientos Legales",
    icono: "bulb",
    dificultad: 1,
    pregunta: "Los vehículos deben obligatoriamente circular en zona urbana en la noche con:",
    opciones: [
      "Luces altas.",
      "Luces bajas.",
      "Sin luces, si hay alumbrado público suficiente.",
    ],
    correcta: 1,
    explicacion: "En zona urbana nocturna es obligatorio circular con luces bajas. Las luces altas solo se usan fuera de zonas urbanas y cuando no hay vehículos en sentido contrario.",
  },
  {
    id: 1104,
    categoria: "Conducta Vial",
    icono: "world",
    dificultad: 2,
    pregunta: "¿Qué daños provoca el dióxido de azufre?",
    opciones: [
      "Daña el sistema nervioso central.",
      "Produce lluvia ácida que daña ecosistemas, edificios y causa problemas respiratorios.",
      "Solo afecta a animales, no a personas.",
    ],
    correcta: 1,
    explicacion: "El dióxido de azufre (SO₂) proveniente de los gases de escape produce lluvia ácida, que daña ecosistemas, corroe edificios y materiales, y provoca enfermedades respiratorias en las personas.",
  },
  {
    id: 1105,
    categoria: "El Individuo en el Tránsito",
    icono: "user",
    dificultad: 1,
    pregunta: "¿Cuál es la segunda causa de muerte en la población joven de Chile?",
    opciones: [
      "Las enfermedades cardíacas.",
      "Los siniestros de tránsito.",
      "El cáncer.",
    ],
    correcta: 1,
    explicacion: "Los siniestros de tránsito son la segunda causa de muerte en la población joven de Chile, después de los suicidios, lo que refleja la gravedad del problema vial en este grupo etario.",
  },
  {
    id: 1106,
    categoria: "Conocimientos Legales",
    icono: "scale",
    dificultad: 2,
    pregunta: "En caso de un siniestro que deja lesionados, ¿quiénes pueden reclamar indemnización al seguro obligatorio?",
    opciones: [
      "Solo el conductor del vehículo asegurado.",
      "Cualquier persona lesionada en el siniestro, incluyendo el conductor.",
      "Solo los pasajeros del vehículo, no los peatones.",
    ],
    correcta: 1,
    explicacion: "El Seguro Obligatorio de Accidentes Personales (SOAP) cubre a cualquier persona lesionada en un siniestro de tránsito, incluyendo al propio conductor, pasajeros y peatones.",
  },
  {
    id: 1107,
    categoria: "El Individuo en el Tránsito",
    icono: "eye",
    dificultad: 2,
    pregunta: "La pérdida de la agudeza visual que se pueda corregir mediante el empleo de lentes, ¿es impedimento para tener licencia de conducir?",
    opciones: [
      "Sí, cualquier pérdida de visión impide obtener la licencia.",
      "No, siempre que se conduzca usando los lentes correctores correspondientes.",
      "Solo es impedimento si afecta un ojo completamente.",
    ],
    correcta: 1,
    explicacion: "La pérdida de agudeza visual corregible con lentes no es impedimento para obtener la licencia, siempre que el conductor use los lentes correctores al conducir, condición que puede quedar indicada en la licencia.",
  },
  {
    id: 1108,
    categoria: "El Individuo en el Tránsito",
    icono: "brain",
    dificultad: 2,
    pregunta: "Si hablamos del desarrollo de la moral, ¿cuál de estas sería una conducta que refleja el estadio más avanzado?",
    opciones: [
      "Respetar las normas solo para evitar una multa.",
      "Respetar las normas porque otros conductores también lo hacen.",
      "Respetar las normas porque se comprende que son necesarias para el bien de todos.",
    ],
    correcta: 2,
    explicacion: "El estadio más avanzado del desarrollo moral implica actuar por convicción propia y comprensión del bien común, no por miedo al castigo ni por imitación de los demás.",
  },
  {
    id: 1109,
    categoria: "El Individuo en el Tránsito",
    icono: "beer",
    dificultad: 2,
    pregunta: "¿Qué significa que una persona tenga 0,31 gramos de alcohol por litro de sangre al conducir?",
    opciones: [
      "Que está en estado de ebriedad según la Ley de Tránsito.",
      "Que está bajo la influencia del alcohol según la Ley de Tránsito.",
      "Que está dentro del límite legal permitido.",
    ],
    correcta: 1,
    explicacion: "Según la Ley de Tránsito chilena, entre 0,3 g/L y 0,79 g/L de alcohol en sangre se considera conducción bajo la influencia del alcohol. El estado de ebriedad comienza desde 0,8 g/L.",
  },
  {
    id: 1110,
    categoria: "Conducta Vial",
    icono: "car",
    dificultad: 3,
    pregunta: "El auto azul circula a 70 km/h y el rojo a 90 km/h. ¿Dónde es más probable que ocurra un siniestro entre ambos?",
    opciones: [
      "En una recta larga y despejada.",
      "Al aproximarse a una curva o intersección donde ambos reducen velocidad de forma diferente.",
      "En una autopista con pistas separadas.",
    ],
    correcta: 1,
    explicacion: "La diferencia de velocidad entre vehículos que circulan juntos es más peligrosa en curvas e intersecciones, donde cada conductor puede reaccionar de forma diferente y con menor margen de maniobra.",
  },
  {
    id: 1111,
    categoria: "Normas de Circulación",
    icono: "corner-up-left",
    dificultad: 2,
    pregunta: "Usted va por una calle de doble sentido de tránsito. Para virar a la izquierda, ¿dónde debe ubicarse?",
    opciones: [
      "Al centro de la pista donde va transitando.",
      "A la derecha de la línea del centro de la calzada.",
      "A la izquierda de la línea del centro de la calzada.",
    ],
    correcta: 1,
    explicacion: "Para virar a la izquierda en una calle de doble sentido, el conductor debe ubicarse a la derecha de la línea central de la calzada, lo más cerca posible de ella, antes de efectuar el viraje.",
  },
  {
    id: 1112,
    categoria: "Conocimientos Legales",
    icono: "shield",
    dificultad: 2,
    pregunta: "¿El seguro obligatorio en el caso de vehículos particulares y motocicletas cubre los daños materiales ocasionados a terceros?",
    opciones: [
      "Sí, cubre tanto daños personales como materiales.",
      "No, el SOAP solo cubre daños personales (lesiones y muerte), no daños materiales.",
      "Solo cubre daños materiales si el monto es inferior a 10 UTM.",
    ],
    correcta: 1,
    explicacion: "El SOAP (Seguro Obligatorio de Accidentes Personales) cubre únicamente daños personales: lesiones y muerte de las víctimas. Los daños materiales a terceros NO están cubiertos por el SOAP.",
  },
  {
    id: 1113,
    categoria: "Conducción Eficiente",
    icono: "gas-station",
    dificultad: 1,
    pregunta: "Una conducción eficiente sirve para:",
    opciones: [
      "Aumentar el consumo de combustible.",
      "Reducir el consumo de combustible, las emisiones contaminantes y el desgaste del vehículo.",
      "Solo para reducir el tiempo de viaje.",
    ],
    correcta: 1,
    explicacion: "La conducción eficiente permite reducir el consumo de combustible, disminuir las emisiones contaminantes y reducir el desgaste mecánico del vehículo, beneficiando al conductor y al medio ambiente.",
  },
  {
    id: 1114,
    categoria: "Conducta Vial",
    icono: "package",
    dificultad: 2,
    pregunta: "Apilar cargas contra el respaldo del pasajero o detrás del asiento provoca:",
    opciones: [
      "Mayor estabilidad del vehículo.",
      "Riesgo de lesiones al pasajero ante una frenada brusca y alteración del centro de gravedad.",
      "Ningún efecto relevante en la seguridad.",
    ],
    correcta: 1,
    explicacion: "Apilar carga detrás o contra los pasajeros es peligroso porque en una frenada brusca la carga puede proyectarse y lesionar a los ocupantes, además de alterar el centro de gravedad del vehículo.",
  },
  {
    id: 1115,
    categoria: "Normas de Circulación",
    icono: "corner-up-left",
    dificultad: 2,
    pregunta: "Usted está en una calle de un solo sentido de tránsito y desea virar a la izquierda. ¿Dónde debe ubicarse?",
    opciones: [
      "En el carril más a la derecha.",
      "En el carril más a la izquierda.",
      "En el carril del centro.",
    ],
    correcta: 1,
    explicacion: "En una calle de un solo sentido, para virar a la izquierda se debe ocupar el carril más a la izquierda disponible, para ejecutar el viraje con seguridad.",
  },
  {
    id: 1116,
    categoria: "Conocimientos Legales",
    icono: "bus",
    dificultad: 2,
    pregunta: "¿Qué es una pista de uso exclusivo?",
    opciones: [
      "Una pista reservada para vehículos de emergencia.",
      "Una pista destinada al uso de un tipo específico de vehículo o usuarios, como buses o bicicletas.",
      "Una pista solo para vehículos pesados.",
    ],
    correcta: 1,
    explicacion: "Una pista de uso exclusivo es aquella destinada al tránsito de un tipo determinado de vehículo o usuario (por ejemplo, buses, taxis o bicicletas), prohibiéndose su uso a otros vehículos.",
  },
  {
    id: 1117,
    categoria: "Convivencia Vial",
    icono: "truck",
    dificultad: 2,
    pregunta: "Usted va detrás de un camión articulado que va a doblar a la derecha hacia una calle angosta. El camión primero gira hacia la izquierda. ¿Qué hace usted?",
    opciones: [
      "Aprovecha el espacio que deja el camión al girar izquierda y lo adelanta por la derecha.",
      "Se detiene y espera que el camión complete su maniobra.",
      "Toca la bocina para que el camión corrija su trayectoria.",
    ],
    correcta: 1,
    explicacion: "Los vehículos largos necesitan girar primero hacia el lado contrario para tener el radio de giro suficiente. Adelantarlo por la derecha en ese momento es muy peligroso. Lo correcto es detenerse y esperar que complete la maniobra.",
  },
  {
    id: 1118,
    categoria: "Mecánica Básica",
    icono: "temperature",
    dificultad: 2,
    pregunta: "¿Cuáles son los sistemas de refrigeración del motor de una motocicleta?",
    opciones: [
      "Solamente aire",
      "Solamente líquido",
      "Solamente líquido y aceite",
      "Solamente líquido y aire",
    ],
    correcta: 3,
    explicacion: "Los motores de motocicleta pueden refrigerarse por aire o por líquido refrigerante. Los sistemas que existen son: solo aire, o líquido y aire combinados. No existe refrigeración exclusiva por aceite.",
  },
  {
    id: 1119,
    categoria: "Normas de Circulación",
    icono: "hourglass-low",
    dificultad: 2,
    pregunta: "La velocidad más baja a la que se puede circular es:",
    opciones: [
      "No existe un límite mínimo de velocidad.",
      "La mitad de la velocidad máxima permitida en esa vía.",
      "La que permita mantener el control del vehículo sin entorpecer el tránsito normal.",
    ],
    correcta: 1,
    explicacion: "La Ley de Tránsito establece que la velocidad mínima es la mitad de la velocidad máxima permitida en esa vía, para no entorpecer el flujo normal del tránsito.",
  },
  {
    id: 1120,
    categoria: "Conducta Vial",
    icono: "rocket",
    dificultad: 2,
    pregunta: "Conducir a una velocidad elevada, ¿afecta la capacidad de anticipación del conductor?",
    opciones: [
      "No, la velocidad no afecta la anticipación.",
      "Sí, a mayor velocidad hay menos tiempo para percibir, procesar y reaccionar ante los peligros.",
      "Solo afecta la anticipación en condiciones de lluvia.",
    ],
    correcta: 1,
    explicacion: "A mayor velocidad, el conductor tiene menos tiempo para percibir los peligros, procesarlos mentalmente y actuar. Esto reduce significativamente la capacidad de anticipación y aumenta el riesgo de siniestro.",
  },

];

/**
 * Genera un examen aleatorio para Clase C (moto)
 * Respeta la misma lógica de puntaje doble que Clase B
 */
export function generarExamenMoto(cantidad = 35) {
  const shuffle = (arr) => {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };

  const dobles = shuffle(PREGUNTAS_MOTO.filter((p) => p.puntaje === 2));
  const simples = shuffle(PREGUNTAS_MOTO.filter((p) => p.puntaje !== 2));

  const selDobles = dobles.slice(0, Math.min(3, dobles.length));
  const selSimples = simples.slice(0, cantidad - selDobles.length);

  return shuffle([...selDobles, ...selSimples]);
}